### ISSUE TITLE
Getting Started REPL Jack-in process exited. Status: 1

### ISSUE THREAD

**Issue by luanprins** [BetterThanTomorrow/calva#1085]
Issue Type: <b>Bug</b>

Fired up the "Getting Started" REPL. Output ended with message "Jack-in process exited. Status: 1". Did not finish jack-in. The ordinary jack-in command, on the other hand, appears to work.

Extension version: 2.0.183
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700 Eight-Core Processor           (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.85GB free)|
|Process Argv|--crash-reporter-id 2feaa930-d56a-4849-8b21-a59342df2207|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry244:30276681
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
pythonvsnew554cf:30281909
pythontb:30265425
pythonvspyt943cf:30280190
wslfolderdoc:30282074
vspre833:30267464
pythonptprofiler:30281270
vshan820cf:30276953

```

</details>

**Comment by PEZ** [comment]
Thanks for reporting!

Adding this here, since relevant:
> Off-band I have been shown that the error message says `java.io.FileNotFoundException <a Windows file path to a user home directory> (Access is denied)

**Comment by luanprins** [comment]
Error text below. The actual path to my home directory is "C:\Users\Prins Luan" so the "Luan" seems missing here:

java -jar ".calva\deps.clj.jar" -Sdeps "{:deps {nrepl/nrepl {:mvn/version,""0.8.3""},cider/cider-nrepl {:mvn/version,""0.25.8""}}}"  -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
Error building classpath. C:\Users\Prins (Access is denied)
java.io.FileNotFoundException: C:\Users\Prins (Access is denied)

        at java.io.FileOutputStream.open0(Native Method)

        at java.io.FileOutputStream.open(Unknown Source)

        at java.io.FileOutputStream.<init>(Unknown Source)

        at clojure.java.io$fn__11498.invokeStatic(io.clj:230)

        at clojure.java.io$fn__11498.invoke(io.clj:230)

        at clojure.java.io$fn__11435$G__11404__11442.invoke(io.clj:69)
        at clojure.java.io$fn__11472.invokeStatic(io.clj:166)
        at clojure.java.io$fn__11472.invoke(io.clj:166)
        at clojure.java.io$fn__11448$G__11400__11455.invoke(io.clj:69)
        at clojure.java.io$writer.invokeStatic(io.clj:119)
        at clojure.java.io$writer.doInvoke(io.clj:104)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)

        at clojure.core$apply.invokeStatic(core.clj:667)

        at clojure.core$spit.invokeStatic(core.clj:6954)

        at clojure.core$spit.doInvoke(core.clj:6954)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.tools.deps.alpha.util.io$write_file.invokeStatic(io.clj:57)
        at clojure.tools.deps.alpha.util.io$write_file.invoke(io.clj:48)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invokeStatic(make_classpath2.clj:126)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invoke(make_classpath2.clj:113)

        at clojure.tools.deps.alpha.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:169)
        at clojure.tools.deps.alpha.script.make_classpath2$_main.doInvoke(make_classpath2.clj:140)

        at clojure.lang.RestFn.applyTo(RestFn.java:137)

        at clojure.lang.Var.applyTo(Var.java:705)

        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.main$main_opt.invokeStatic(main.clj:514)
        at clojure.main$main_opt.invoke(main.clj:510)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)

        at clojure.main.main(main.java:40)

Jack-in process exited. Status: 1

**Comment by PEZ** [comment]
Can you run that command in the VS Code terminal and see if you get the error?

**Comment by luanprins** [comment]
Tried that now, got a different error (see end of this comment). The terminal it's linked to is PowerShell. I do know that PowerShell requires quotation marks around a path containing spaces; was wonder if the previous error signified that Calva was inputting without quotation marks?

PS C:\Users\Prins Luan> java -jar ".calva\deps.clj.jar" -Sdeps "{:deps {nrepl/nrepl {:mvn/version,""0.8.3""},cider/cider-nrepl {:mvn/version,""0.25.8""}}}" -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
Error: Unable to access jarfile .calva\deps.clj.jar

**Comment by PEZ** [comment]
Thanks! Yes, it needs to be run from inside the Calva extension itself ... On Mac and Linux the command line includes the whole path, but on Windows things are a bit different...

**Comment by luanprins** [comment]
Update: using PowerShell terminal in VSCode, I attempted to run the command within the temp directory created by Calva when starting up this REPL.

My input:

PS C:\Users\Prins Luan\AppData\Local\Temp\betterthantomorrow.calva\cefxc> java -jar ".calva\deps.clj.jar" -Sdeps "{:deps {nrepl/nrepl {:mvn/version,""0.8.3""},cider/cider-nrepl {:mvn/version,""0.25.8""}}}" -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"

Resulting output (different error):

Error while parsing option "--config-data {:deps {nrepl/nrepl {:mvn/version,0.8.3},cider/cider-nrepl {:mvn/version,0.25.8}}}": java.lang.NumberFormatException: Invalid number: 0.8.3

Conversely, doing the same using the Command Prompt terminal in VSCode, I get the same output as originally posted, excluding the last line reporting "Jack-in process exited. Status: 1"

**Comment by luanprins** [comment]
Update: Standalone REPL has the same error.

**Comment by borkdude** [comment]
@luanprins The above is just a quoting issue. This works in PS for me:

```
java -jar .\target\deps.clj-0.0.13-standalone.jar -Sdeps '{:deps {nrepl/nrepl {:mvn/version,\"0.8.3\"},cider/cider-nrepl {:mvn/version,\"0.25.8\"}}}' -m nrepl.cmdline --middleware '[cider.nrepl/cider-middleware]'
```

**Comment by borkdude** [comment]
Can't repro any problem in a dir with spaces:

``` 
PS C:\Temp\with spaces> java -jar deps.clj-0.0.13-standalone.jar -Sdeps '{:deps {nrepl/nrepl {:mvn/version,\"0.8.3\"},cider/cider-nrepl {:mvn/version,\"0.25.8\"}}}' -m nrepl.cmdline --middleware '[cider.nrepl/cider-middleware]'
nREPL server started on port 65370 on host kubernetes.docker.internal - nrepl://kubernetes.docker.internal:65370
```

**Comment by luanprins** [comment]
@borkdude Tried what worked for you on PowerShell and this came up.

Error: Unable to access jarfile .\target\deps.clj-0.0.13-standalone.jar

Is this familiar to you?

**Comment by PEZ** [comment]
@luanprins you'll need to use a path to some `deps.clj.jar` file that you have.

But the quoting issue is a separate thing. Try remove that from the picture first. So if you run this from a project where jack-in has failed:

```sh
java -jar .calva\deps.clj.jar
```

And then copy `deps.clj.jar` to a directory that does not have spaces in the path and from that directory run:

```sh
java -jar deps.clj.jar
```

What do you get for those two experiments?

**Comment by luanprins** [comment]
@PEZ 
Both of those got the same error, which is below, although the second directory did not have spaces (directory was C:\tmp).

`Error building classpath. C:\Users\Prins (Access is denied)
java.io.FileNotFoundException: C:\Users\Prins (Access is denied)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
        at clojure.java.io$fn__11498.invokeStatic(io.clj:230)
        at clojure.java.io$fn__11498.invoke(io.clj:230)
        at clojure.java.io$fn__11435$G__11404__11442.invoke(io.clj:69)
        at clojure.java.io$fn__11472.invokeStatic(io.clj:166)
        at clojure.java.io$fn__11472.invoke(io.clj:166)
        at clojure.java.io$fn__11448$G__11400__11455.invoke(io.clj:69)
        at clojure.java.io$writer.invokeStatic(io.clj:119)
        at clojure.java.io$writer.doInvoke(io.clj:104)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$spit.invokeStatic(core.clj:6954)
        at clojure.core$spit.doInvoke(core.clj:6954)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.tools.deps.alpha.util.io$write_file.invokeStatic(io.clj:57)
        at clojure.tools.deps.alpha.util.io$write_file.invoke(io.clj:48)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invokeStatic(make_classpath2.clj:126)      
        at clojure.tools.deps.alpha.script.make_classpath2$run.invoke(make_classpath2.clj:113)
        at clojure.tools.deps.alpha.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:169)    
        at clojure.tools.deps.alpha.script.make_classpath2$_main.doInvoke(make_classpath2.clj:140)        
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.main$main_opt.invokeStatic(main.clj:514)
        at clojure.main$main_opt.invoke(main.clj:510)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:40)`

**Comment by PEZ** [comment]
I wonder why it looks for files in your user folder...

**Comment by PEZ** [comment]
I have now bought a small PC. It was worth it. I can reproduce!

With a user named/home directory`Peter Strömberg`:

```sh
C:\Users\Public>java -jar .\deps.clj.jar
Error building classpath. C:\Users\Peter (Access is denied)
java.io.FileNotFoundException: C:\Users\Peter (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at clojure.java.io$fn__11498.invokeStatic(io.clj:230)
        at clojure.java.io$fn__11498.invoke(io.clj:230)
        at clojure.java.io$fn__11435$G__11404__11442.invoke(io.clj:69)
        at clojure.java.io$fn__11472.invokeStatic(io.clj:166)
        at clojure.java.io$fn__11472.invoke(io.clj:166)
        at clojure.java.io$fn__11448$G__11400__11455.invoke(io.clj:69)
        at clojure.java.io$writer.invokeStatic(io.clj:119)
        at clojure.java.io$writer.doInvoke(io.clj:104)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$spit.invokeStatic(core.clj:6954)
        at clojure.core$spit.doInvoke(core.clj:6954)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at clojure.tools.deps.alpha.util.io$write_file.invokeStatic(io.clj:57)
        at clojure.tools.deps.alpha.util.io$write_file.invoke(io.clj:48)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invokeStatic(make_classpath2.clj:126)
        at clojure.tools.deps.alpha.script.make_classpath2$run.invoke(make_classpath2.clj:113)
        at clojure.tools.deps.alpha.script.make_classpath2$_main.invokeStatic(make_classpath2.clj:169)
        at clojure.tools.deps.alpha.script.make_classpath2$_main.doInvoke(make_classpath2.clj:140)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.main$main_opt.invokeStatic(main.clj:514)
        at clojure.main$main_opt.invoke(main.clj:510)
        at clojure.main$main.invokeStatic(main.clj:664)
        at clojure.main$main.doInvoke(main.clj:616)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Var.applyTo(Var.java:705)
        at clojure.main.main(main.java:40)
```

**Comment by borkdude** [comment]
I have a created a Windows user with the name `Peter Strömberg` but can't reproduce this.

<img width="692" alt="Screenshot 2021-04-14 at 09 46 17" src="https://user-images.githubusercontent.com/284934/114674039-19e98b80-9d07-11eb-8191-0630a5bd1b81.png">
<img width="337" alt="Screenshot 2021-04-14 at 09 50 56" src="https://user-images.githubusercontent.com/284934/114674047-1b1ab880-9d07-11eb-914f-36898e7751aa.png">

**Comment by PEZ** [comment]
Seems my repro is a bit lucky. On another machine, the same user name does not cause any problems.

**Comment by PEZ** [comment]
Ah, yeah, didn't see your comment, @borkdude . On that machine. 😄

**Comment by bpringe** [comment]
Does this have to do with PS being started as admin? IIRC... one way to do this is shift-right-click Poweshell in the start menu then select "Run as Administrator." The `sudo` of Windows...

**Comment by borkdude** [comment]
Please try again with deps.clj 0.0.14:

https://github.com/borkdude/deps.clj/releases/tag/v0.0.14

**Comment by PEZ** [comment]
Works like a charm, @borkdude !

Here's a Calva VSIX bundling this new `deps.clj`: https://12881-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.188-1085-deps-clj-windows-space-0096b3e7.vsix

Will release a new Calva with this now, I think. But if I decide not to, you can give that VSIX a spin, @luanprins . You will need to choose to create new files when the Getting Started REPL asks about that, because otherwise you will be using old `deps.clj`.

**Comment by tigerinus** [comment]
<img width="2248" height="528" alt="Image" src="https://github.com/user-attachments/assets/f854bfe0-8b23-43d1-9b59-3ddc61b9cd26" />

having the same issue with latest version (see screenshot) - my username does contain a space in it.

how can I workaround this?

**Comment by PEZ** [comment]
@tigerinus: I think this is what @TheRealMintd fixes in 
* #2970 

Which has now been merged and released. Please upgrade to Calva v2.0.545 and let me know how you fare.

**Comment by tigerinus** [comment]
> [@tigerinus](https://github.com/tigerinus): I think this is what [@TheRealMintd](https://github.com/TheRealMintd) fixes in
> 
> * [Handle spaces in path when jacking-in #2970](https://github.com/BetterThanTomorrow/calva/pull/2970)
> 
> Which has now been merged and released. Please upgrade to Calva v2.0.545 and let me know how you fare.

Thanks for the response.

I should be using latest build, as I just started to learn Clojure last week.

I see no quotes surrounding the path that contains my username with a space in it, which I believe is what caused the problem.

**Comment by PEZ** [comment]
Sorry for the radio silence. I missed that you hade replied, @tigerinus. Do you stil have this problem? What Calva version are you using?
