### ISSUE TITLE
Jack-in not working

### ISSUE THREAD

**Issue by lpeletan** [BetterThanTomorrow/calva#1139]
Since yesterday (2021-04-21) I am unable to jack-in.
ctrl+opt+c  ctrl+opt+j   => nothing happens

When I open the developer console (help -> toggle developer tools -> console) I see that the following error appears every time I try to jack-in:

> [Extension Host] An error occurred while initializing project directory. TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type function ([AsyncFunction])
	at validateString (internal/validators.js:120:11)
	at Object.resolve (path.js:980:7)
	at /Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1093374
	at Generator.next (<anonymous>)
	at /Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1090699
	at new Promise (<anonymous>)
	at r (/Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1090444)
	at /Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1093130
	at Object.<anonymous> (/Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1093592)
	at Generator.next (<anonymous>)
	at /Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1090699
	at new Promise (<anonymous>)
	at r (/Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1090444)
	at Object.t.initProjectDir (/Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1092914)
	at /Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1042064
	at Generator.next (<anonymous>)
	at /Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1037795
	at new Promise (<anonymous>)
	at r (/Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1037540)
	at t.jackInCommand (/Users/lpeletan/.vscode/extensions/betterthantomorrow.calva-2.0.192/out/extension.js:2:1041987)
	at S._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:106770)
	at S.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:86:107208)
	at u._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12794)
	at u._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:12478)
	at u._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:11145)
	at u._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:9931)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:8032
	at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at E.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:29750
	at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at E.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15496)
	at t._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20754)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17640
	at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1836)
	at acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12861)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12209
	at Socket.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:105:13173)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)

I tried the following actions to fix the issue:
- Install an older version of Calva
- Uninstall Calva completely and install it again
- reset my Calva settings in VSCode
- Restart VSCode
- Restart computer

None of them and no combination of them helped.

MacOS BigSur 11.2.3
VSCode 1.55.2
Calva 2.0.192 (but I tried to revert back to older versions, down to 2.0.144, with the same issue)

Any help would be greatly appreciated.

**Comment by PEZ** [comment]
Very strange that an older Calva wouldn't help. Maybe try using VS Code Insiders? If that works, it could mean that something about your VS Code installation has been borked.

**Comment by lpeletan** [comment]
I just tried the previous stable version of VSCode (v1.54.3) and it's now working fine.
So my guess is that the issue arose when my VSCode auto updated from 1.55.1 to 1.55.2
One of my colleagues had the exact same issue and was able to solve it by installing the latest insider version of VSCode.

**Comment by PEZ** [comment]
Oh, that doesn't sound good. I mean, I'm happy it works for you two, but it sounds like there might be a lot of people having troubles right now. Let's leave this issue open for now. At least it has workarounds mentioned.

**Comment by PEZ** [comment]
I haven't seen any more reports around this so closing this for now. We can reopen if we see any new reports about it.

**Comment by lpeletan** [comment]
I found something interesting.
The workaround that I mentioned earlier (installing an older version of VSCode) actually stopped working after a restart.
But I just found out that if I disable the Python extension (the one from Microsoft) then the problem vanishes.
So, for some reason there is some incompatibility between Calva and the Python extension.

**Comment by bpringe** [comment]
Well that is really strange... I wonder what the Python extension could be doing to cause an issue...
