### ISSUE TITLE
Jack-in als live share guest not working (polylith repo)

### ISSUE THREAD

**Issue by svdo** [BetterThanTomorrow/calva#1625]
In one of the last versions up to v2.0.257 this stopped working. I don't know which one exactly.

We're using polylith.

When trying to connect to the remote REPL as a live share guest, I'm presented with a list of project roots. The paths are correct, but different from local. Locally, the paths are absolute paths from the root of my file system. Over live share the paths are absolute from the root of the workspace. For example, locally I might have `/Users/my/my-project` and when connecting over live share that would show up as `/`.

I choose ‘/’, then I'm asked for the type, I choose ‘generic’, and then nothing…

**Comment by PEZ** [comment]
Thanks! 🙏 

> one of the last versions up to v2.0.257

Just to understand this. The projects root menu was added in 257. But this stopped working before that?

Also. When you say the paths are correct, but different from local. That confuses me a bit. The glass if half-full, so I should take it as they are correct, right? 😄 

Do you usually choose 'generic' as the project type? Do you see the options there that you would expect?

**Comment by PEZ** [comment]
@svdo Can you run Calva in the debugger and see if `await vsls.getApi()` ever resolves for you? I guess it does, since you get a project type prompt, but anyway.

I'm asking because of: https://github.com/MicrosoftDocs/live-share/issues/4551 which is causing #1569.

**Comment by svdo** [comment]
@PEZ Yes that `await vsls.getApi()` resolves for me.

I have run this scenario in the debugger, the live share guest that is. A couple of observations.

## clojure-lsp error

This one happens right on joining the Live Share session, before trying to connect the REPL or something.

```
Clojure-lsp zip file downloaded to [/Users/stefanmm/Documents/Projects/3dparty/calva/clojure-lsp-native-macos-amd64.zip]()
src/lsp/download.ts:61
Unzipping file
src/lsp/download.ts:86
[emma-mono[/RunTestListener]()] Jest process "watch-tests" ended unexpectedly
/Users/stefanmm/.vscode/extensions/orta.vscode-jest-4.2.1/out/extension.js:2
Writing version file
src/lsp/download.ts:76
Starting clojure-lsp at [/Users/stefanmm/Documents/Projects/3dparty/calva/clojure-lsp]()
src/lsp/main.ts:403
clojure[/serverInfo/raw]() failed: Error: Internal error.
    at handleResponse ([/Users/stefanmm/Documents/Projects/3dparty/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48]())
    at processMessageQueue ([/Users/stefanmm/Documents/Projects/3dparty/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17]())
    at Immediate.<anonymous> ([/Users/stefanmm/Documents/Projects/3dparty/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13]())
    at processImmediate ([/Users/stefanmm/Documents/Projects/3dparty/calva/lib/internal/timers.js:464:21]())
    at process.callbackTrampoline (node:internal[/async_hooks:130:17]()) {code: -32603, data: 'java.lang.RuntimeException: java.lang.reflect.…r.serverInfoRaw(server.clj:135)
	... 15 more
', stack: 'Error: Internal error.
    at handleResponse …Trampoline (node:internal[/async_hooks:130:17]())', message: 'Internal error.'}

arg1:Error: Internal error.\n    at handleResponse ([/Users/stefanmm/Documents/Projects/3dparty/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48]())\n    at processMessageQueue ([/Users/stefanmm/Documents/Projects/3dparty/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17]())\n    at Immediate.<anonymous> ([/Users/stefanmm/Documents/Projects/3dparty/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13]())\n    at processImmediate (node:internal[/timers:464:21]())\n    at process.callbackTrampoline (node:internal[/async_hooks:130:17]()) {code: -32603, data: 'java.lang.RuntimeException: java.lang.reflect.…r.serverInfoRaw(server.clj:135)\n\t... 15 more\n', stack: 'Error: Internal error.\n    at handleResponse …Trampoline (node:internal[/async_hooks:130:17]())', message: 'Internal error.'}
code:-32603
data:'java.lang.RuntimeException: java.lang.reflect.InvocationTargetException\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)\n\tat org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)\n\tat org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)\n\tat org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessa…lj:20)\n\tat clojure_lsp.feature.format$resolve_user_cljfmt_config.invoke(format.clj:19)\n\tat clojure_lsp.handlers$server_info$fn__34629.invoke(handlers.clj:262)\n\tat clojure_lsp.handlers$server_info.invokeStatic(handlers.clj:261)\n\tat clojure_lsp.handlers$server_info.invoke(handlers.clj:253)\n\tat clojure.lang.Var.invoke(Var.java:380)\n\tat clojure_lsp.handlers.ClojureLSPFeatureHandler.server_info_raw(handlers.clj:532)\n\tat clojure_lsp.server.ClojureLspServer.serverInfoRaw(server.clj:135)\n\t... 15 more...
message:'Internal error.'
stack:'Error: Internal error.\n    at handleResponse ([/Users/stefanmm/Documents/Projects/3dparty/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48]())\n    at processMessageQueue ([/Users/stefanmm/Documents/Projects/3dparty/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17]())\n    at Immediate.<anonymous> ([/Users/stefanmm/Documents/Projects/3dparty/calva/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13]())\n    at processImmediate (node:internal[/timers:464:21]())\n    at process.callbackTrampoline (node:internal[/async_hooks:130:17]())'
[[Prototype]]:Error
<anonymous> @ [/Applications/Visual]() Studio Code.app[/Contents/Resources/app/out/bootstrap-fork.js:5:6]()
```

Screenshot:

<img width="1454" alt="Screenshot 2022-04-02 at 10 50 11" src="https://user-images.githubusercontent.com/4028554/161375411-f4642d7f-fcb5-403a-9388-24a4c040c6e6.png">

The call stack of the internal responseMessage.error:

```
"java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
  at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
  at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
  at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
  at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
  at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
  at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
  at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  at java.util.concurrent.FutureTask.run(FutureTask.java:264)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.lang.Thread.run(Thread.java:829)
  at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
  at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
Caused by: java.lang.reflect.InvocationTargetException
  at java.lang.reflect.Method.invoke(Method.java:566)
  at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
  ... 13 more
Caused by: java.lang.NullPointerException
  at clojure.string$starts_with_QMARK_.invokeStatic(string.clj:365)
  at clojure.string$starts_with_QMARK_.invoke(string.clj:361)
  at clojure_lsp.shared$uri__GT_filename.invokeStatic(shared.clj:161)
  at clojure_lsp.shared$uri__GT_filename.invoke(shared.clj:156)
  at clojure_lsp.feature.format$resolve_user_cljfmt_config.invokeStatic(format.clj:20)
  at clojure_lsp.feature.format$resolve_user_cljfmt_config.invoke(format.clj:19)
  at clojure_lsp.handlers$server_info$fn__34629.invoke(handlers.clj:262)
  at clojure_lsp.handlers$server_info.invokeStatic(handlers.clj:261)
  at clojure_lsp.handlers$server_info.invoke(handlers.clj:253)
  at clojure.lang.Var.invoke(Var.java:380)
  at clojure_lsp.handlers.ClojureLSPFeatureHandler.server_info_raw(handlers.clj:532)
  at clojure_lsp.server.ClojureLspServer.serverInfoRaw(server.clj:135)
  ... 15 more
"
```

So I guess clojure-lsp doesn't like live share? Well I already knew that I guess, but maybe good to solve at some point.

## Error when connecting REPL

This one is probably why the REPL connection is not working:

```
rejected promise not handled within 1 second: Unknown (FileSystemError) (FileSystemError): Error: EROFS: read-only file system, mkdir '[/.calva]()'
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104
stack trace: Unknown (FileSystemError) (FileSystemError): Error: EROFS: read-only file system, mkdir '[/.calva]()'
    at Function._handleError ([/Applications/Visual]() Studio Code.app[/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:88571]())
    at Object.createDirectory ([/Applications/Visual]() Studio Code.app[/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:86821]())
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal[/process/task_queues:96:5]())
```

Screenshot:

<img width="1450" alt="Screenshot 2022-04-02 at 10 51 28" src="https://user-images.githubusercontent.com/4028554/161375507-b4bfa7c2-2605-411b-b28f-c8512ac11284.png">

I'm not sure how to proceed. I don't know why this `mkdir` is being called and what triggers it. It should not happen of course, because it should be the remote workspace's `.calva` folder that is being used (and already exists) it seems to me.

**Comment by PEZ** [comment]
I wish I could test it, but LiveShare doesn't work at all for me because of that promise not resolving...

**Comment by PEZ** [comment]
The mkdir is probably from here:

https://github.com/BetterThanTomorrow/calva/blob/dev/src/results-output/results-doc.ts#L124

**Comment by svdo** [comment]
> I wish I could test it, but LiveShare doesn't work at all for me because of that promise not resolving...

Are you running on Windows? You could try developing in WSL2, my colleagues seem to be having good results that way...

**Comment by PEZ** [comment]
No, I hate Windows! I'm using Mac.
