### ISSUE TITLE
clojure-lsp fails to download for some Apple M1 users

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1761]
We introduced a regression in v2.0.281 for some Apple M1 users using a VS Code Apple Silicon binary.

* #1758

For now, probably best for this user category to use v2.0.280.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/30010/171992842-1d5260a2-7017-4e89-aeb1-431bc71bb942.png">

**Comment by ferdinand-beyer** [comment]
This is the full console output I get when trying to start `clojure-lsp` via the `Start Clojure LSP Server` command:

```
workbench.desktop.main.js:71
[Extension Host] rejected promise not handled within 1 second: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
E @ workbench.desktop.main.js:71
$logExtensionHostMessage @ workbench.desktop.main.js:1719
_doInvokeHandler @ workbench.desktop.main.js:1719
_invokeHandler @ workbench.desktop.main.js:1719
_receiveRequest @ workbench.desktop.main.js:1719
_receiveOneMessage @ workbench.desktop.main.js:1719
(anonymous) @ workbench.desktop.main.js:1719
invoke @ workbench.desktop.main.js:67
deliver @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
invoke @ workbench.desktop.main.js:67
deliver @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
O @ workbench.desktop.main.js:3170
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199

workbench.desktop.main.js:71 [Extension Host] stack trace: TypeError: The "path" argument must be of type string. Received undefined
	at new NodeError (node:internal/errors:371:5)
	at validateString (node:internal/validators:119:11)
	at Object.join (node:path:1172:7)
	at /Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:434903
	at /Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:436531
	at Generator.next (<anonymous>)
	at /Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:430716
	at new Promise (<anonymous>)
	at l (/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:430461)
	at I (/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:434663)
	at /Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:433956
	at Generator.next (<anonymous>)
	at i (/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:430518)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)

E @ workbench.desktop.main.js:71
$logExtensionHostMessage @ workbench.desktop.main.js:1719
_doInvokeHandler @ workbench.desktop.main.js:1719
_invokeHandler @ workbench.desktop.main.js:1719
_receiveRequest @ workbench.desktop.main.js:1719
_receiveOneMessage @ workbench.desktop.main.js:1719
(anonymous) @ workbench.desktop.main.js:1719
invoke @ workbench.desktop.main.js:67
deliver @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
invoke @ workbench.desktop.main.js:67
deliver @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
O @ workbench.desktop.main.js:3170
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199

workbench.desktop.main.js:2670
[[object Object]]The "path" argument must be of type string. Received undefined
$onExtensionRuntimeError @ workbench.desktop.main.js:2670
_doInvokeHandler @ workbench.desktop.main.js:1719
_invokeHandler @ workbench.desktop.main.js:1719
_receiveRequest @ workbench.desktop.main.js:1719
_receiveOneMessage @ workbench.desktop.main.js:1719
(anonymous) @ workbench.desktop.main.js:1719
invoke @ workbench.desktop.main.js:67
deliver @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
invoke @ workbench.desktop.main.js:67
deliver @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
O @ workbench.desktop.main.js:3170
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199

workbench.desktop.main.js:2670
TypeError: The "path" argument must be of type string. Received undefined
	at new NodeError (node:internal/errors:371:5)
	at validateString (node:internal/validators:119:11)
	at Object.join (node:path:1172:7)
	at vscode-file://vscode-app/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:434903
	at vscode-file://vscode-app/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:436531
	at Generator.next (<anonymous>)
	at vscode-file://vscode-app/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:430716
	at new Promise (<anonymous>)
	at l (vscode-file://vscode-app/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:430461)
	at I (vscode-file://vscode-app/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:434663)
	at vscode-file://vscode-app/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:433956
	at Generator.next (<anonymous>)
	at i (vscode-file://vscode-app/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:430518)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
$onExtensionRuntimeError @ workbench.desktop.main.js:2670
_doInvokeHandler @ workbench.desktop.main.js:1719
_invokeHandler @ workbench.desktop.main.js:1719
_receiveRequest @ workbench.desktop.main.js:1719
_receiveOneMessage @ workbench.desktop.main.js:1719
(anonymous) @ workbench.desktop.main.js:1719
invoke @ workbench.desktop.main.js:67
deliver @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
invoke @ workbench.desktop.main.js:67
deliver @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
O @ workbench.desktop.main.js:3170
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199

workbench.desktop.main.js:71 [Extension Host] Error getting ns form of this file using docMirror, trying with cljs.reader: Error: Missing mirror document!

workbench.desktop.main.js:71 [Extension Host] Error parsing ns form of this file. #error {:message "resolve-symbol is not implemented", :data {:type :reader-exception, :sym start}, :cause #error {:message "resolve-symbol is not implemented", :data {:sym start}}}

workbench.desktop.main.js:71 [Extension Host] Error getting ns form of this file using docMirror, trying with cljs.reader: Error: Missing mirror document!

workbench.desktop.main.js:71 [Extension Host] Error parsing ns form of this file. #error {:message "resolve-symbol is not implemented", :data {:type :reader-exception, :sym start}, :cause #error {:message "resolve-symbol is not implemented", :data {:sym start}}}

workbench.desktop.main.js:71 [Extension Host] Error getting ns form of this file using docMirror, trying with cljs.reader: Error: Missing mirror document!

workbench.desktop.main.js:71 [Extension Host] Error parsing ns form of this file. #error {:message "resolve-symbol is not implemented", :data {:type :reader-exception, :sym start}, :cause #error {:message "resolve-symbol is not implemented", :data {:sym start}}}

workbench.desktop.main.js:594   ERR Missing mirror document!: Error: Missing mirror document!
	at Object.g [as getDocument] (/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:386020)
	at Object.o [as getFormSelection] (/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:535463)
	at a (/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:551266)
	at c (/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:551387)
	at Object.e.currentContext (/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:552633)
	at /Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:518529
	at Generator.next (<anonymous>)
	at i (/Users/fbeyer/.vscode/extensions/betterthantomorrow.calva-2.0.281/out/extension.js:2:517285)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by PEZ** [comment]
Here's a VSIX that should restore the old behaviour of using amd64 binaries for Apple Silicon builds of VS Code. https://output.circle-artifacts.com/output/job/da06411d-45e4-4e7e-aca4-5c8f41deeff1/artifacts/0/tmp/artifacts/calva-2.0.282-1761-apple-m1-clojure-lsp-8463a2bc.vsix

I don't think it fixes the crash you have there @ferdinand-beyer, because I could not reproduce it. But you can try the VSIX anyway and see if we're in a better place.

**Comment by PEZ** [comment]
It turned out there is an old bug we happened to uncover with v2.0.281. If JAVA_HOME is not set, we fail to start the clojure-lsp fallback jar. That bug is not fixed yet. What closed this issue was that we restored the behaviour of Calva to download and use the Intel binary. Which then Rosetta 2 handles.
