### ISSUE TITLE
Property test failure - tokenizing literal unicode characters

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1814]
https://app.circleci.com/pipelines/github/BetterThanTomorrow/calva/5349/workflows/35d49d95-ef97-4df6-bb65-cd00a5d3ec17/jobs/23905

<details>
<pre>
  1) Scanner
       simple
         tokenizes literal characters
           tokenizes literal unicode characters:
     Property failed after 83 tests
{ seed: 2143097431, path: "82:13", endOnFailure: true }
Counterexample: ["\\ "]
Shrunk 1 time(s)
Got error: Error: expect(received).toBe(expected) // Object.is equality

Expected: "\\ "
Received: "\\"

Stack trace: Error: expect(received).toBe(expected) // Object.is equality

Expected: "\\ "
Received: "\\"
    at /home/circleci/calva/src/extension-test/unit/cursor-doc/clojure-lexer-test.ts:331:35
    at Property.predicate (/home/circleci/calva/node_modules/fast-check/lib/check/property/Property.generated.js:16:105)
    at Property.run (/home/circleci/calva/node_modules/fast-check/lib/check/property/Property.generic.js:20:31)
    at runIt (/home/circleci/calva/node_modules/fast-check/lib/check/runner/Runner.js:21:32)
    at check (/home/circleci/calva/node_modules/fast-check/lib/check/runner/Runner.js:113:11)
    at Object.assert (/home/circleci/calva/node_modules/fast-check/lib/check/runner/Runner.js:117:15)
    at Context.<anonymous> (/home/circleci/calva/src/extension-test/unit/cursor-doc/clojure-lexer-test.ts:327:12)
    at callFn (/home/circleci/calva/node_modules/mocha/lib/runnable.js:366:21)
    at Test.Runnable.run (/home/circleci/calva/node_modules/mocha/lib/runnable.js:354:5)
    at Runner.runTest (/home/circleci/calva/node_modules/mocha/lib/runner.js:678:10)
    at /home/circleci/calva/node_modules/mocha/lib/runner.js:801:12
    at next (/home/circleci/calva/node_modules/mocha/lib/runner.js:593:14)
    at /home/circleci/calva/node_modules/mocha/lib/runner.js:603:7
    at next (/home/circleci/calva/node_modules/mocha/lib/runner.js:486:14)
    at Immediate._onImmediate (/home/circleci/calva/node_modules/mocha/lib/runner.js:571:5)
    at processImmediate (node:internal/timers:464:21)

Hint: Enable verbose mode in order to have the list of all failing values encountered during the run
  Error: Property failed after 83 tests
  { seed: 2143097431, path: "82:13", endOnFailure: true }
  Counterexample: ["\\   "]
  Shrunk 1 time(s)
  Got error: Error: expect(received).toBe(expected) // Object.is equality
  
  Expected: "\\   "
  Received: "\\"
  
  Stack trace: Error: expect(received).toBe(expected) // Object.is equality
  
  Expected: "\\   "
  Received: "\\"
      at /home/circleci/calva/src/extension-test/unit/cursor-doc/clojure-lexer-test.ts:331:35
      at Property.predicate (node_modules/fast-check/lib/check/property/Property.generated.js:16:105)
      at Property.run (node_modules/fast-check/lib/check/property/Property.generic.js:20:31)
      at runIt (node_modules/fast-check/lib/check/runner/Runner.js:21:32)
      at check (node_modules/fast-check/lib/check/runner/Runner.js:113:11)
      at Object.assert (node_modules/fast-check/lib/check/runner/Runner.js:117:15)
      at Context.<anonymous> (src/extension-test/unit/cursor-doc/clojure-lexer-test.ts:327:12)
      at processImmediate (node:internal/timers:464:21)
</pre>
</details>

**Comment by bpringe** [comment]
CC @PEZ
