### ISSUE TITLE
Calva installation fail

### ISSUE THREAD

**Issue by Risord** [BetterThanTomorrow/calva#1874]
Environment:
- Windows 10
- VS Code 1.57.1
- OpenJDK (build 11.0.16+8-adhoc..jdk11u)

Extensions seems to install just fine but it's dead.
For example you can see "Calva Format: Dedent Line" action but it does pop VS code error:
`Command 'Calva Format: Dedent Line' resulted in an error (command 'calva-fmt.tabDedent' not found)`

Log (Extension Host) from installation:
```
[2022-09-23 03:01:20.030] [exthost] [info] ExtensionService#_doActivateExtension betterthantomorrow.calva {"startup":false,"extensionId":{"value":"betterthantomorrow.calva","_lower":"betterthantomorrow.calva"},"activationEvent":"onLanguage:clojure"}
[2022-09-23 03:01:20.030] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/[USER-NAME]/.vscode/extensions/betterthantomorrow.calva-2.0.244/out/extension
[2022-09-23 03:01:20.126] [exthost] [error] Activating extension betterthantomorrow.calva failed due to an error:
[2022-09-23 03:01:20.126] [exthost] [error] TypeError: Cannot read property 'createTestController' of undefined
	at c:\Users\[USER-NAME]\.vscode\extensions\betterthantomorrow.calva-2.0.244\out\extension.js:2:390013
	at Generator.next (<anonymous>)
	at i (c:\Users\[USER-NAME]\.vscode\extensions\betterthantomorrow.calva-2.0.244\out\extension.js:2:388628)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by Risord** [comment]
Ok crash happen because VsCode test API is not available due it's 1.59+ feature.
=> Updated vs code and it started working.

**Comment by PEZ** [comment]
Thanks for updating about the cause. I thought we had set the required VS Code version higher than 1.59. Will have to check that...

**Comment by bpringe** [comment]
We have this in the package.json:

```json
  "engines": {
    "node": ">=16",
    "vscode": "^1.67.0"
  },
```

Maybe at some point in the past we didn't update that property appropriately (like after adding test API code), and @Risord was on a version of Calva that had the test API code before we updated `engines.vscode` appropriately - just a guess.
