### ISSUE TITLE
Unable to get Jack-In to work

### ISSUE THREAD

**Issue by micahasmith** [BetterThanTomorrow/calva#1875]
Hi everyone! Having issues getting calva to work.

OS:  macOS 12.5.1
VSC: 1.71.2
Java: openjdk 17.0.2 2022-01-18
Clojure: Clojure CLI version 1.11.1.1165

Even when I run "Fire up the getting started REPL" I get:

```
java -jar '/Users/micahsmith/.vscode/extensions/betterthantomorrow.calva-2.0.304/deps.clj.jar' -Sdeps '{:deps {nrepl/nrepl {:mvn/version,"1.0.0"},cider/cider-nrepl {:mvn/version,"0.28.5"}}}' -M -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware]"
nREPL server started on port 56933 on host localhost - nrepl://localhost:56933
ERROR: Unhandled REPL handler exception processing message {:op eval, :code *ns*, :id 1}
Syntax error macroexpanding at (cider/nrepl/inlined_deps/orchard/v0v9v2/orchard/java/parser.clj:1:1).
        at clojure.lang.Compiler.load(Compiler.java:7665)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6908.invoke(core.clj:6161)
        at clojure.core$load.invokeStatic(core.clj:6160)
        at clojure.core$load.doInvoke(core.clj:6144)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5933)
        at clojure.core$load_one.invoke(core.clj:5928)
        at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
        at clojure.core$load_lib.invokeStatic(core.clj:5974)
        at clojure.core$load_lib.doInvoke(core.clj:5953)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6016)
        at clojure.core$load_libs.doInvoke(core.clj:6000)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6038)
        at clojure.core$require.doInvoke(core.clj:6038)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3714)
        at clojure.lang.Compiler$BodyExpr.eval(Compiler.java:6151)
        at clojure.lang.Compiler$IfExpr.eval(Compiler.java:2741)
        at clojure.lang.Compiler$DefExpr.eval(Compiler.java:457)
        at clojure.lang.Compiler.eval(Compiler.java:7199)
        at clojure.lang.Compiler.load(Compiler.java:7653)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6908.invoke(core.clj:6161)
        at clojure.core$load.invokeStatic(core.clj:6160)
        at clojure.core$load.doInvoke(core.clj:6144)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5933)
        at clojure.core$load_one.invoke(core.clj:5928)
        at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
        at clojure.core$load_lib.invokeStatic(core.clj:5974)
        at clojure.core$load_lib.doInvoke(core.clj:5953)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6016)
        at clojure.core$load_libs.doInvoke(core.clj:6000)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6038)
        at clojure.core$require.doInvoke(core.clj:6038)
        at clojure.lang.RestFn.invoke(RestFn.java:619)
        at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.info$eval4249$loading__6789__auto____4250.invoke(info.clj:1)
        at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.info$eval4249.invokeStatic(info.clj:1)
        at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.info$eval4249.invoke(info.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7194)
        at clojure.lang.Compiler.eval(Compiler.java:7183)
        at clojure.lang.Compiler.load(Compiler.java:7653)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6908.invoke(core.clj:6161)
        at clojure.core$load.invokeStatic(core.clj:6160)
        at clojure.core$load.doInvoke(core.clj:6144)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5933)
        at clojure.core$load_one.invoke(core.clj:5928)
        at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
        at clojure.core$load_lib.invokeStatic(core.clj:5974)
        at clojure.core$load_lib.doInvoke(core.clj:5953)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6016)
        at clojure.core$load_libs.doInvoke(core.clj:6000)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6038)
        at clojure.core$require.doInvoke(core.clj:6038)
        at clojure.lang.RestFn.invoke(RestFn.java:930)
        at cider.nrepl.middleware.stacktrace$eval4241$loading__6789__auto____4242.invoke(stacktrace.clj:1)
        at cider.nrepl.middleware.stacktrace$eval4241.invokeStatic(stacktrace.clj:1)
        at cider.nrepl.middleware.stacktrace$eval4241.invoke(stacktrace.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7194)
        at clojure.lang.Compiler.eval(Compiler.java:7183)
        at clojure.lang.Compiler.load(Compiler.java:7653)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6908.invoke(core.clj:6161)
        at clojure.core$load.invokeStatic(core.clj:6160)
        at clojure.core$load.doInvoke(core.clj:6144)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5933)
        at clojure.core$load_one.invoke(core.clj:5928)
        at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
        at clojure.core$load_lib.invokeStatic(core.clj:5974)

        at clojure.core$load_lib.doInvoke(core.clj:5953)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6016)
        at clojure.core$load_libs.doInvoke(core.clj:6000)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6038)
        at clojure.core$require.doInvoke(core.clj:6038)
        at clojure.lang.RestFn.invoke(RestFn.java:1289)
        at cider.nrepl.middleware.debug$eval3824$loading__6789__auto____3825.invoke(debug.clj:1)
        at cider.nrepl.middleware.debug$eval3824.invokeStatic(debug.clj:1)
        at cider.nrepl.middleware.debug$eval3824.invoke(debug.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7194)
        at clojure.lang.Compiler.eval(Compiler.java:7183)
        at clojure.lang.Compiler.load(Compiler.java:7653)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6908.invoke(core.clj:6161)
        at clojure.core$load.invokeStatic(core.clj:6160)
        at clojure.core$load.doInvoke(core.clj:6144)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5933)
        at clojure.core$load_one.invoke(core.clj:5928)
        at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
        at clojure.core$load_lib.invokeStatic(core.clj:5974)
        at clojure.core$load_lib.doInvoke(core.clj:5953)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6016)
        at clojure.core$load_libs.doInvoke(core.clj:6000)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6038)
        at clojure.core$require.doInvoke(core.clj:6038)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at cider.nrepl$handler_future$fn__2305$fn__2306.invoke(nrepl.clj:53)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1990)
        at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1990)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at cider.nrepl$handler_future$fn__2305.invoke(nrepl.clj:52)
        at clojure.lang.Delay.deref(Delay.java:42)
        at clojure.core$deref.invokeStatic(core.clj:2337)
        at clojure.core$deref.invoke(core.clj:2323)
        at cider.nrepl$wrap_debug$fn__2388.invoke(nrepl.clj:163)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at cider.nrepl$wrap_enlighten$fn__2396.invoke(nrepl.clj:190)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at nrepl.middleware.session$add_stdin$fn__1416.invoke(session.clj:370)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at nrepl.middleware.sideloader$wrap_sideloader$fn__1921.invoke(sideloader.clj:108)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at nrepl.middleware.load_file$wrap_load_file$fn__1840.invoke(load_file.clj:81)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at nrepl.middleware.caught$wrap_caught$fn__1231.invoke(caught.clj:97)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at cider.nrepl.middleware.content_type$handle_content_type.invokeStatic(content_type.clj:144)
        at cider.nrepl.middleware.content_type$handle_content_type.invoke(content_type.clj:131)
        at clojure.lang.Var.invoke(Var.java:388)
        at cider.nrepl$wrap_content_type$fn__2346.invoke(nrepl.clj:107)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at nrepl.middleware.print$wrap_print$fn__1198.invoke(print.clj:234)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at cider.nrepl$wrap_undef$fn__2518.invoke(nrepl.clj:493)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at cider.nrepl.middleware.track_state$handle_tracker.invokeStatic(track_state.clj:244)
        at cider.nrepl.middleware.track_state$handle_tracker.invoke(track_state.clj:242)
        at clojure.lang.Var.invoke(Var.java:388)
        at cider.nrepl$wrap_tracker$fn__2510.invoke(nrepl.clj:482)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at cider.nrepl$wrap_xref$fn__2536.invoke(nrepl.clj:514)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at cider.nrepl$wrap_profile$fn__2454.invoke(nrepl.clj:343)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at nrepl.middleware.session$session$fn__1401.invoke(session.clj:325)
        at nrepl.middleware$wrap_conj_descriptor$fn__962.invoke(middleware.clj:16)
        at nrepl.server$default_handler$fn__1969.invoke(server.clj:141)
        at nrepl.server$handle_STAR_.invokeStatic(server.clj:24)
        at nrepl.server$handle_STAR_.invoke(server.clj:21)
        at nrepl.server$handle$fn__1937.invoke(server.clj:41)
        at clojure.core$binding_conveyor_fn$fn__5823.invoke(core.clj:2047)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: jdk.javadoc.doclet.Doclet
        at java.base/java.net.URLClassLoader.findClass(Unknown Source)
        at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at clojure.lang.RT.classForName(RT.java:2209)
        at clojure.lang.RT.classForNameNonLoading(RT.java:2222)
        at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.java.parser$eval4444$loading__6789__auto____4445.invoke(parser.clj:1)
        at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.java.parser$eval4444.invokeStatic(parser.clj:1)
        at cider.nrepl.inlined_deps.orchard.v0v9v2.orchard.java.parser$eval4444.invoke(parser.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7194)
        at clojure.lang.Compiler.eval(Compiler.java:7183)
        at clojure.lang.Compiler.load(Compiler.java:7653)
        ... 187 more
```

**Comment by micahasmith** [comment]
I rebooted my computer and it worked 💁🏻‍♂️

**Comment by PEZ** [comment]
Thanks for updating! Very strange with these kind of errors... I don't know if you first tried with restarting VS Code?

**Comment by micahasmith** [comment]
I didn't and I definitely should've haha

**Comment by PEZ** [comment]
For anyone finding this issue and who has a similar problem. There are several layers of state that can be corrupt:

1. **The VS Code Window** - This is where Calva (or any extension) store session state. Calva is pretty stateful, so at times it can help to reload the window. (There's a command for this: **Developer: Reload Window**).
   Keep in mind that while VS Code internal Terminals ”survive” a window reload, Calva's Jack-in terminal doesn't. If you want your REPL to survive a reload, start it manually in an integrated terminal (or some other terminal outside VS Code, of course). Calva has a command for copying out the Jack-in command it would use: **Calva: Copy Jack-in Command to Clipboard**.
1. **VS Code** - Restarting of VS Code sometimes works. Recently someone had to make a complete clean-out of VS Code and install it anew to have an nREPL feature start working. Some Calva persistent state lives here. (Though nothing that should have the potential to stop Calva from working.)
1. **The OS** – It has happened that an OS reboot has been the only way to get things working again. I guess that sometimes the OS can lock up things in a way so that a VS Code restart can't start clean enough.

We have been seeing a bit more of these utterly strange errors lately. Seems like it could be regressions in VS Code. Let's hope they manage to quickly rebuild the quality we used to enjoy!
