### ISSUE TITLE
`actual command NOT FOUND` when trying to insert suggested import

### ISSUE THREAD

**Issue by otwieracz** [BetterThanTomorrow/calva#1993]
### Steps to reproduce
No steps to reproduce unfortunately, as there wasn't anything specific and after VSCodium restart it worked fine in exactly the same location.

After trying to add suggested import (via `cmd + .` menu, _Quick Fix_) for `[taoensso.timbre :as log]` I got an error `actual command NOT FOUND`.

Stacktrace:
```
2022-12-08 16:10:55.993 [error] [betterthantomorrow.calva] provider FAILED
2022-12-08 16:10:55.993 [error] Error: Missing mirror document!
	at Object.g [as getDocument] (/Users/slawekgonet/.vscode-oss/extensions/betterthantomorrow.calva-2.0.321-universal/out/extension.js:2:393945)
	at Object.o [as getFormSelection] (/Users/slawekgonet/.vscode-oss/extensions/betterthantomorrow.calva-2.0.321-universal/out/extension.js:2:550537)
	at a (/Users/slawekgonet/.vscode-oss/extensions/betterthantomorrow.calva-2.0.321-universal/out/extension.js:2:567572)
	at c (/Users/slawekgonet/.vscode-oss/extensions/betterthantomorrow.calva-2.0.321-universal/out/extension.js:2:567693)
	at e.currentContext (/Users/slawekgonet/.vscode-oss/extensions/betterthantomorrow.calva-2.0.321-universal/out/extension.js:2:569558)
	at /Users/slawekgonet/.vscode-oss/extensions/betterthantomorrow.calva-2.0.321-universal/out/extension.js:2:533192
	at Generator.next (<anonymous>)
	at i (/Users/slawekgonet/.vscode-oss/extensions/betterthantomorrow.calva-2.0.321-universal/out/extension.js:2:531966)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-12-08 16:11:03.246 [error] actual command NOT FOUND __vsclbf62szc undefined
```

### Version
- Calva
```
Calva is utilizing cider-nrepl and clojure-lsp to create this VS Code experience.
  nREPL dependencies configured:
    nrepl: 1.0.0
    cider-nrepl: 0.28.5
    cider/piggieback: 0.5.3
  clojure-lsp version configured: latest

If you are new to Calva, please see: https://calva.io/getting-started/
  And please consider the command: **Calva: Fire up the Getting Started REPL**

Calva version used: v2.0.321
clojure-lsp version used: 2022.11.03-00.16.44-nightly
clj-kondo version used: 2022.11.02
```

- VSCodium:
```

Version: 1.73.1
Release: 22314
Commit: 14f2d26367b7e8f03ff2352516ba27d6302dd7b1
Date: 2022-11-10T18:10:38.644Z (3 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```

**Comment by PEZ** [comment]
Thanks for reporting! Let's see if we can get in some more clues about this from other users.
