### ISSUE TITLE
Cursor moves back to start of indented line when typing inside parens on a new line

### ISSUE THREAD

**Issue by LouDnl** [BetterThanTomorrow/calva#2071]
As discussed in this thread on Slack: https://clojurians.slack.com/archives/CBE668G4R/p1675855895843909

When working in VSCode on Windows 11 the cursor gets moved back to the start of an indented line inside a parens code block.
short gif of te problem when working inside a comment codeblock: 
![checkditdan2](https://user-images.githubusercontent.com/8543038/217754193-0dd814ec-7a6c-4a03-8364-dd121868f34d.gif)
![checkditdan](https://user-images.githubusercontent.com/8543038/217754070-a44ba4b9-9e14-41ca-9c1b-83795d9b3d0f.gif)

Tested with VSCode latest release and with VSCode 1.76.0-insider with Calva as the only enabled extension.
Jacked-in to project and having the project running in the background.

Will test more to get a gif from when it happens outside a comment block but inside a parens code block

**Comment by PEZ** [comment]
Thanks for reporting. Trying a thing now. As I can't reproduce the problem on my machine, I am hoping you will be ready to test a custom Calva build soon, @LouDnl. 🙏

**Comment by LouDnl** [comment]
@PEZ sure no problem

**Comment by PEZ** [comment]
Here's the custom build that might fix the issue. Please give it a spin:

* https://output.circle-artifacts.com/output/job/85547ee0-bd5b-46a3-abc9-d94c3af6fb3f/artifacts/0/tmp/artifacts/calva-2.0.332-pez-displaced-edits-d857a819.vsix

See [Installing VSIX Packages](https://github.com/BetterThanTomorrow/calva/wiki/Testing-VSIX-Packages#installing-a-vsix-package) if you are not familiar with how that works.

**Comment by PEZ** [comment]
Here's a new VSIX, with a blind attempt to await a promise + some debug logging. It will log out some relevant configuration parameters in the VS Code Developer console. These log entries include `Issue #2071` to make them easier to find. Please give it a spin!

* https://output.circle-artifacts.com/output/job/0a6b5b3e-d293-4eb0-910f-ebaf1ce38900/artifacts/0/tmp/artifacts/calva-2.0.332-pez-displaced-edits-04faf37b.vsix

**Comment by LouDnl** [comment]
Still happens in a comment, not outside a comment but! I just noticed it's doing this in files that are outside my main project folder. At first I thought it was because I exclude files/folders in a config.edn for kondo and a config.edn for lsp, but it didnt happen after creating a clojure file inside an excluded folder inside my main project folder. I then proceeded to create a new clojure file in a folder outside my main project folder and it still didnt happen in- or outside a comment... damn.
So back to the file where it did happen and viewing the developer tools, here's the error message:
```shell
console.ts:137 [Extension Host] No ns form found.
log.ts:313   ERR Cannot read properties of undefined (reading 'catch'): TypeError: Cannot read properties of undefined (reading 'catch')
	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-d857a819\out\extension.js:2:543928
	at Generator.next (<anonymous>)
	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-d857a819\out\extension.js:2:542120
	at new Promise (<anonymous>)
	at l (c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-d857a819\out\extension.js:2:541865)
	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-d857a819\out\extension.js:2:543827
	at e.default.<anonymous> (c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-d857a819\out\extension.js:2:544203)
	at Generator.next (<anonymous>)
	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-d857a819\out\extension.js:2:542120
	at new Promise (<anonymous>)
	at l (c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-d857a819\out\extension.js:2:541865)
	at e.default.provideCompletionItems (c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-d857a819\out\extension.js:2:543759)
	at te.provideCompletionItems (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:51894)
	at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:77036
	at Z._withAdapter (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:67207)
	at Z.$provideCompletionItems (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:77011)
	at o._doInvokeHandler (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13691)
	at o._invokeHandler (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13373)
	at o._receiveRequest (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12092)
	at o._receiveOneMessage (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10845)
	at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8952
	at w.invoke (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at b.deliver (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at p.fire (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at c.fire (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19006)
	at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:17079
	at w.invoke (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at b.deliver (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at p.fire (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at c.fire (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19006)
	at i._receiveMessage (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:23593)
	at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:21127
	at w.invoke (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at b.deliver (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at p.fire (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at p.acceptChunk (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15837)
	at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:14967
	at Socket.l (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:26303)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by LouDnl** [comment]
I just noticed its the wrong version, here's with the newer version:
Startup error:
```shell
mainThreadExtensionService.ts:80 TypeError: Cannot read properties of null (reading '1')
	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-04faf37b\out\extension.js:2:569085
	at ChildProcess.exithandler (node:child_process:397:7)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Socket.<anonymous> (node:internal/child_process:450:11)
	at Socket.emit (node:events:390:28)
	at Pipe.<anonymous> (node:net:687:12)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
fire @ ipc.net.ts:638
_receiveMessage @ ipc.net.ts:959
(anonymous) @ ipc.net.ts:832
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
acceptChunk @ ipc.net.ts:382
(anonymous) @ ipc.net.ts:338
E @ ipc.net.ts:70
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
console.ts:137 [Extension Host] Latest deps.clj.jar version: v1.11.1.1208
```
error the moment the cursor jumps:
```shell
ERR Cannot read properties of undefined (reading 'catch'): TypeError: Cannot read properties of undefined (reading 'catch')
	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-04faf37b\out\extension.js:2:544276
	at Generator.next (<anonymous>)
	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-04faf37b\out\extension.js:2:542468
	at new Promise (<anonymous>)
	at l (c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-04faf37b\out\extension.js:2:542213)
	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-04faf37b\out\extension.js:2:544175
	at e.default.<anonymous> (c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-04faf37b\out\extension.js:2:544551)
	at Generator.next (<anonymous>)
	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-04faf37b\out\extension.js:2:542468
	at new Promise (<anonymous>)
	at l (c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-04faf37b\out\extension.js:2:542213)
	at e.default.provideCompletionItems (c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-04faf37b\out\extension.js:2:544107)
	at te.provideCompletionItems (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:51894)
	at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:77036
	at Z._withAdapter (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:67207)
	at Z.$provideCompletionItems (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:87:77011)
	at o._doInvokeHandler (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13691)
	at o._invokeHandler (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:13373)
	at o._receiveRequest (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:12092)
	at o._receiveOneMessage (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:10845)
	at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:95:8952
	at w.invoke (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at b.deliver (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at p.fire (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at c.fire (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19006)
	at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:111:17079
	at w.invoke (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at b.deliver (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at p.fire (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at c.fire (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:19006)
	at i._receiveMessage (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:23593)
	at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:21127
	at w.invoke (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:145)
	at b.deliver (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:2266)
	at p.fire (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:61:1844)
	at p.acceptChunk (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:15837)
	at f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:14967
	at Socket.l (f:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:69:26303)
	at Socket.emit (node:events:390:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Comment by PEZ** [comment]
> ```shell
> log.ts:313   ERR Cannot read properties of undefined (reading 'catch'): TypeError: Cannot read properties of undefined (reading 'catch')
> 	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-d857a819\out\extension.js:2:543928
> 	at Generator.next (<anonymous>)
> 	at c:\Users\thier\.vscode\extensions\betterthantomorrow.calva-2.0.332-pez-displaced-edits-d857a819\out\extension.js:2:542120
...
> ```

Here's a VSIX fixing this particular bug. Which I don't think is causing the problems with displaced edits.

* https://output.circle-artifacts.com/output/job/5edc43c2-7ad4-47ea-91d1-7b8f5df27ca0/artifacts/0/tmp/artifacts/calva-2.0.332-pez-displaced-edits-eb11e612.vsix
