### ISSUE TITLE
Error when using "Calva Format: Format and Align Current Form" shortcut in VSCode

### ISSUE THREAD

**Issue by LouDnl** [BetterThanTomorrow/calva#2231]
I frequently use the  "Calva Format: Format and Align Current Form" shortcut in VSCode, which is a great tool btw.

When trying to format a map that has a key value pair where said value contains a namespaced keyword the formatting doesn't work.

An error is thrown in the developer tools:
```typescript
ERR Namespaced keywords not supported !

ERR [Extension Host] Error in `formatIndex`: Namespaced keywords not supported !

[Extension Host] Error in `formatIndex`: Namespaced keywords not supported ! (at console.<anonymous> (d:\Beheer\_portable-tools\programming\VSCode-Insider\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:151752))
S @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:862
deliver @ event.ts:1075
fire @ event.ts:1031
fire @ ipc.net.ts:650
Q.onmessage @ localProcessExtensionHost.ts:583

[Extension Host] rejected promise not handled within 1 second: Namespaced keywords not supported ! (at console.<anonymous> (d:\Beheer\_portable-tools\programming\VSCode-Insider\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:151752))
S @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:862
deliver @ event.ts:1075
fire @ event.ts:1031
fire @ ipc.net.ts:650
Q.onmessage @ localProcessExtensionHost.ts:583
```

Example non working where :action value contains a namespaced keyword:
```clojure
{:action (ring/path-for ::login {:customer-slug customer-slug})
:method  :post
:data-form-type "other"}
```
Example working where the namespace is written:
```clojure
{:action        (ring/path-for :my.namespace/login {:customer-slug customer-slug})
:method         :post
:data-form-type "other"}
```

**Comment by PEZ** [comment]
This is due to that the version of rewrite-cljs used does not support auto-namespaced keywords:

https://github.com/clj-commons/rewrite-cljs/blob/master/src/rewrite_clj/node/keyword.cljs#L16

This feature in Calva is built on an old fork suffering from this and many more limitations. Things will not improve until align-associative is a feature in the main distribution of cljfmt. For which there is hope now:

* https://github.com/weavejester/cljfmt/pull/299

Also see https://calva.io/formatting/#about-aligning-associative-forms
