### ISSUE TITLE
Missing mirror document

### ISSUE THREAD

**Issue by pekeler** [BetterThanTomorrow/calva#2311]
I'm seeing a few of these errors in the Extension Host output:

```
2023-09-12 14:04:36.256 [error] Error: Missing mirror document!
    at Object.getDocument (/Users/pekeler/.vscode/extensions/betterthantomorrow.calva-2.0.388/src/doc-mirror/index.ts:216:11)
    at Object.getFormSelection (/Users/pekeler/.vscode/extensions/betterthantomorrow.calva-2.0.388/src/select.ts:18:28)
    at _currentFormText (/Users/pekeler/.vscode/extensions/betterthantomorrow.calva-2.0.388/src/util/get-text.ts:16:34)
    at currentFormText (/Users/pekeler/.vscode/extensions/betterthantomorrow.calva-2.0.388/src/util/get-text.ts:30:10)
    at Object.currentClojureContext (/Users/pekeler/.vscode/extensions/betterthantomorrow.calva-2.0.388/src/util/get-text.ts:172:36)
    at /Users/pekeler/.vscode/extensions/betterthantomorrow.calva-2.0.388/src/providers/hover.ts:56:20
    at Generator.next (<anonymous>)
    at u (/Users/pekeler/.vscode/extensions/betterthantomorrow.calva-2.0.388/src/providers/definition.ts:111:3)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```
I haven't noticed anything not working, though.

**Comment by PEZ** [comment]
We shouldn't be throwing these in this form if nothing bad is happening.
