### ISSUE TITLE
Linting failing on wsl

### ISSUE THREAD

**Issue by agoldhammer** [BetterThanTomorrow/calva#248]
I am using Calva on WSL. When I try to lint with joker using the command palette, I get this:
Command 'Calva: Lint current file' is not enabled in the current context.

If I try ctrl-alt-c, L, I get a message saying this is not a command.

useWSL is enabled in settings, with lint on save enabled.

I have tried different settings for the joker path, including none, joker, /usr/local/bin, /usr/local/bin/, and /usr/local/bin/joker. None seems to work.

joker run from the command line works fine.

**Comment by PEZ** [comment]
Hello, I'm sorry about that. I don't think this is specific to WSL or joker. It's a more general issue with commands not being available.

I'll have a look and see what i find.

**Comment by agoldhammer** [comment]
Thanks!

**Comment by PEZ** [comment]
@agoldhammer, Right, much later, but anyway. Can you give the latest Calva a spin and see if this issue is resolved for you?

**Comment by agoldhammer** [comment]
@PEZ : No, but the error message is different. With Calva 2.0.30 installed, it now says "Running contributed command "calva:lintFile" failed." Previously it said this was not a command. Progress! :)

**Comment by agoldhammer** [comment]
@PEZ : I'm not sure about the instruction in settings that the path must be set to a valid WSL path. My joker is in /usr/local/bin, and I tried setting this to joker, /usr/local/bin/joker, and /usr/local/bin. Same error in all cases. Do I need to find the Windows 10 path to this directory?

**Comment by PEZ** [comment]
Hmmm. I can run the linter if I set the path to the directory in which the joker binary is found. (`/home/linuxbrew/.linuxbrew/bin` in my case).

Can you open the Developer Console (Help menu in VS Code) and see if you get any more clues there as to what is going wrong?

**Comment by agoldhammer** [comment]
@PEZ : [object Object]]Can't resolve windows filepath to wsl path: Path must be an absolute windows path
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60

Looks like I need to figure out what Windows path corresponds to /usr/local/bin in WSL. By the way, on my Linux box and Macpro, linting works just fine. It's just WSL that is giving the problem. I'll try to figure this out when I have a moment. Thanks for your help. Love Calva, by the way.

**Comment by agoldhammer** [comment]
@PEZ: More info:
Linux path must reside in /mnt/: Error: Linux path must reside in /mnt/
	at t.parsePosixPath (/home/agold/.vscode-server/extensions/betterthantomorrow.calva-2.0.30/out/extension.js:135:180608)
	at v (/home/agold/.vscode-server/extensions/betterthantomorrow.calva-2.0.30/out/extension.js:135:179716)
	at y (/home/agold/.vscode-server/extensions/betterthantomorrow.calva-2.0.30/out/extension.js:135:179969)
	at Object.t.wslToWindows (/home/agold/.vscode-server/extensions/betterthantomorrow.calva-2.0.30/out/extension.js:135:178479)
	at t.WslDefinitionProvider.<anonymous> (/home/agold/.vscode-server/extensions/betterthantomorrow.calva-2.0.30/out/extension.js:135:177875)
	at Generator.next (<anonymous>)
	at o (/home/agold/.vscode-server/extensions/betterthantomorrow.calva-2.0.30/out/extension.js:135:176788)
	at process._tickCallback (internal/process/next_tick.js:68:7)

I tried using wslpath -w /usr/local/bin to get a Windows path, but the path reported didn't work. I also copied joker into /mnt/c/Users/Public and used that as a path, with and without final slash and with and without joker name appended. Didn't work.

**Comment by xanatos1992** [comment]
Okay so on my setup i got it working i think.
I put joker in /usr/bin/joker 
also make sure you can execute it example: wsl joker in powershell or something
in calva i just activated usage of wsl, the joker path is just joker

**Comment by agoldhammer** [comment]
@PEZ @xanatos1992 : It doesn't work for me. joker is in /usr/local/bin . Path is set to "joker." joker can be run from bash: joker --lint <file>.clj works fine. joker can also be run from PowerShell with wsl joker, as you suggest. But in Calva, ctrl-alt-c L yields "Running the contributed 'calva.lintFile' failed."

Does the following info help resolve the issue:
mainThreadExtensionService.ts:60 [[object Object]]Cannot read property 'length' of null
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
mainThreadExtensionService.ts:61 TypeError: Cannot read property 'length' of null
	at e.subscriptions.push.r.window.onDidChangeActiveTextEditor.e (/home/agold/.vscode-server/extensions/betterthantomorrow.calva-2.0.30/out/extension.js:135)
	at u.fire (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:48)
	at _extHostDocumentsAndEditors.onDidChangeActiveTextEditor.e (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:599)
	at u.fire (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:48)
	at u.$acceptDocumentsAndEditorsDelta (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:535)
	at d._doInvokeHandler (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:653)
	at d._invokeHandler (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:653)
	at d._receiveRequest (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:652)
	at d._receiveOneMessage (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:651)
	at _protocol.onMessage.e (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:649)
	at u.fire (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:48)
	at a (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:177)
	at e (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:177)
	at u.fire (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:48)
	at e.onMessage.e (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:758)
	at u.fire (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:48)
	at a (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:177)
	at e (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:177)
	at u.fire (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:48)
	at y._receiveMessage (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:186)
	at _socketDisposables.push._socketReader.onMessage.e (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:183)
	at u.fire (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:48)
	at f.acceptChunk (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:180)
	at _register._socket.onData.e (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:179)
	at Socket.t (/home/agold/.vscode-server/bin/2213894ea0415ee8c85c5eea0d0ff81ecc191529/out/vs/server/remoteExtensionHostProcess.js:188)
	at Socket.emit (events.js:182)
	at addChunk (_stream_readable.js:283)
	at readableAddChunk (_stream_readable.js:264)
	at Socket.Readable.push (_stream_readable.js:219)
	at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94)

**Comment by agoldhammer** [comment]
Also, I get this warning on starting nrepl. I don't know if it's relevant or not:
nREPL server started on port 51519 on host 127.0.0.1 - nrepl://127.0.0.1:51519
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by mranderson049.orchard.v0v4v0.dynapath.v0v2v5.dynapath.defaults$eval3868$fn__3869 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of mranderson049.orchard.v0v4v0.dynapath.v0v2v5.dynapath.defaults$eval3868$fn__3869
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by xanatos1992** [comment]
@agoldhammer  The warning it self is okay.
I guess i found the problematic line here.
In lint.ts:67 `if (data.length != 0)`
That is the case when the joker Process throws something in tho stderr output.
But i dont know why the data that gets send by joker is null or even if it is the correct position.

Because the exception is the minimized version of the source code so it is hard to understand where the error really occures
Maybe @PEZ has some idea to better pin point the problem or if this is even the problematic line.

**Comment by PEZ** [comment]
@agoldhammer , How did you install joker. Which version is it, btw?

@xanatos1992, good find! We can at least improve the error reporting here. :smile:

**Comment by agoldhammer** [comment]
@PEZ : agold@lenny:~/Prog/maze$ joker --version
v0.12.5

I installed by downloading a precompiled binary from https://github.com/candid82/joker/releases.

**Comment by agoldhammer** [comment]
@PEZ: I've figured this out. Unchecking "use WSL" makes linting work, nrepl still works, and everything seems to be as it should even though I am in fact using WSL. Perhaps the new version of WSL works differently. I notice from the source code that you are running joker as "wsl joker," but "wsl joker" does not run from my bash shell in ConEmu. It does run from a Windows command prompt or PowerShell. Perhaps that's the problem. But I think you can close this issue.

**Comment by PEZ** [comment]
@agoldhammer : wow. Thanks for investigating and reporting about your solution.

I think this issue should be kept open because a solution like _untick `useWSL` to make it work with WSL_ is a bit too crazy for me. 😜 We will have to take a good look at this and see if we can fix it in Calva.

**Comment by agoldhammer** [comment]
@PEZ : For what it's worth, I'm using Windows version 1903, installed 7/28/2019, build 18362.267. I wouldn't have thought of unchecking the "use WSL" box except that I looked at the Calva source and saw that, when that box was checked, you were prepending "wsl" to the joker path before executing, so I wondered what would happen if I unchecked it. I hope this doesn't disrupt any other part of the code.

**Comment by andresrgz** [comment]
I worked on adding the support for WSL when things were a little different with Visual Studio Code. Before, the [Remote Development Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack) didn't exist, so that's why it was necessary to prepend the `wsl` to the joker path.

Now that this extension exists, the `useWSL` is no longer necessary. This should definitely be reworked.

**Comment by PEZ** [comment]
Please do! There are people fighting this beast on the Calva-dev channel right now, actually. I feel I am leaving them hanging, so your assistance would be much appreciated! ❤️

**Comment by agoldhammer** [comment]
Just unclicking useWSL worked for me.

**Comment by bpringe** [comment]
Now that linting is done with clj-kondo, is this still an issue?

**Comment by PEZ** [comment]
Yeah, closing this now. clj-kondo + the Remote extension should cover this, if I am correctly informed.
