### ISSUE TITLE
JDK 11 support

### ISSUE THREAD

**Issue by rbeesley** [BetterThanTomorrow/calva#72]
```
C:\Users\[REDACTED]\.lein> lein repl
Error loading cider.piggieback: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/util.cljc:1:1)
Exception in thread "Thread-1" java.lang.RuntimeException: Unable to resolve var: cider.piggieback/wrap-cljs-repl in this context, compiling:(NO_SOURCE_PATH:0:0)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
        at clojure.lang.Compiler.analyze(Compiler.java:6669)
        at clojure.lang.Compiler.analyze(Compiler.java:6625)
        at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3834)
...
        at clojure.core$bound_fn_STAR_$fn__4671.doInvoke(core.clj:1911)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Unable to resolve var: cider.piggieback/wrap-cljs-repl in this context
        at clojure.lang.Util.runtimeException(Util.java:221)
        at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:710)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
        ... 44 more
REPL server launch timed out.
C:\Users\[REDACTED]\.lein>
```

Can be fixed with this update to profiles.clj.

```
{:repl {:plugins [[cider/cider-nrepl "0.18.0"]]
        :dependencies [[org.clojure/tools.nrepl "0.2.13"]
                       [cider/piggieback "0.3.9"]
                       [figwheel-sidecar "0.5.16"]
                       [javax.xml.bind/jaxb-api "2.4.0-b180830.0359"] ; Required as of JDK11
                       [org.glassfish.jaxb/jaxb-runtime "2.4.0-b180830.0438"]] ; Required as of JDK11
        :repl-options {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]}}}
```

I was also having this problem with JDK10, so I came up with this solution rather than rolling back to JDK8.

I came up with this fix after seeing the [project.clj for clj-symphony](https://github.com/symphonyoss/clj-symphony/blob/master/project.clj). I don't know if the versions are ideal, and there are WARNINGS when I start the repl, but it looks like maybe this is working. It certainly gets me past the error which wouldn't let me start the repl.

**Comment by PEZ** [comment]
Thanks! I'll leave this issue open for people to find it until I have figured out if it should go into the documentation somewhere.

**Comment by xanatos1992** [comment]
I guess this can be closed already. 
It works right now with even jdk12 out of the box.

@PEZ @rbeesley
