### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by metehan** [BetterThanTomorrow/calva#748]
```
c:\Users\Root\.vscode\extensions\betterthantomorrow.calva-2.0.119\out\extension.js:9
 */(function(){var i="Expected a function",a="__lodash_placeholder__",l=[["ary",128],["bind",1],["bindKey",2],["curry",8],["curryRight",16],["flip",512],["partial",32],["partialRight",64],["rearg",256]],o="[object Arguments]",s="[object Array]",u="[object Boolean]",c="[object Date]",f="[object Error]",p="[object Function]",h="[object GeneratorFunction]",d="[object Map]",m="[object Number]",g="[object Object]",v="[object RegExp]",w="[object Set]",b="[object String]",y="[object Symbol]",k="[object WeakMap]",x="[object ArrayBuffer]",j="[object DataView]",_="[object Float32Array]",E="[object Float64Array]",T="[object Int8Array]",S="[object Int16Array]",A="[object Int32Array]",z="[object Uint8Array]",I="[object Uint16Array]",C="[object Uint32Array]",P=/\b__p \+= '';/g,F=/\b(__p \+=) '' \+/g,D=/(__e\(.*?\)|\b__t\)) \+\n'';/g,B=/&(?:amp|lt|gt|quot|#39);/g,R=/[&<>"']/g,O=RegExp(B.source),q=RegExp(R.source),V=/<%-([\s\S]+?)%>/g,L=/<

[TypeError: Cannot read property 'getTokenCursor' of undefined
	at c:\Users\Root\.vscode\extensions\betterthantomorrow.calva-2.0.119\out\extension.js:9:271629
	at Array.forEach (<anonymous>)
	at Q (c:\Users\Root\.vscode\extensions\betterthantomorrow.calva-2.0.119\out\extension.js:9:271580)
	at Timeout.M [as _onTimeout] (c:\Users\Root\.vscode\extensions\betterthantomorrow.calva-2.0.119\out\extension.js:9:270848)
	at listOnTimeout (internal/timers.js:531:17)
	at processTimers (internal/timers.js:475:7)]

abstractExtensionService.ts:166 Extension host terminated unexpectedly. Code:  1  Signal:  null
_onExtensionHostCrashed @ abstractExtensionService.ts:166

notificationsAlerts.ts:40 Extension host terminated unexpectedly.
```

**Comment by bpringe** [comment]
Hello! Can you give some details around this error? What were you doing when it occurred?

**Comment by metehan** [comment]
This happened many times randomly during my work. I was connected shadow-cljs repl but I wasn't doing anything particular. I shared this because I thought this error can mean something to you.

**Comment by bpringe** [comment]
This looks troublesome indeed, but I've not experienced it myself. Can you provide steps to reproduce the error?

**Comment by bpringe** [comment]
Closing for now. We can reopen if the issue resurfaces.
