### ISSUE TITLE
Error when start a REPL with jdk15

### ISSUE THREAD

**Issue by Kineolyan** [BetterThanTomorrow/calva#888]
## Report

When jack-in a REPL from vs-code with calva, I got the following error:
```
java.lang.NullPointerException: Cannot invoke "jdk.javadoc.internal.doclets.formats.html.HtmlConfiguration.getOptions()" because "this.configuration" is null
        at jdk.javadoc/jdk.javadoc.internal.doclets.formats.html.HtmlDoclet.getSupportedOptions(HtmlDoclet.java:292)
        at jdk.javadoc/jdk.javadoc.doclet.StandardDoclet.getSupportedOptions(StandardDoclet.java:93)
        at cider.nrepl.inlined_deps.orchard.v0v5v5.orchard.java.parser$parse_java$reify__7885.getSupportedOptions(parser.clj:77)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.getSupportedOptionsOf(Start.java:645)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.consumeDocletOption(Start.java:593)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseArgs(Start.java:799)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.parseAndExecute(Start.java:497)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:399)
        at jdk.javadoc/jdk.javadoc.internal.tool.Start.begin(Start.java:361)
        at jdk.javadoc/jdk.javadoc.internal.api.JavadocTaskImpl.call(JavadocTaskImpl.java:104)
        at cider.nrepl.inlined_deps.orchard.v0v5v5.orchard.java.parser$parse_java.invokeStatic(parser.clj:87)
        at cider.nrepl.inlined_deps.orchard.v0v5v5.orchard.java.parser$parse_java.invoke(parser.clj:64)
        at cider.nrepl.inlined_deps.orchard.v0v5v5.orchard.java.parser$source_info.invokeStatic(parser.clj:299)
        at cider.nrepl.inlined_deps.orchard.v0v5v5.orchard.java.parser$source_info.invoke(parser.clj:290)
        at clojure.lang.Var.invoke(Var.java:384)
        at cider.nrepl.inlined_deps.orchard.v0v5v5.orchard.java$class_info_STAR_.invokeStatic(java.clj:196)
        at cider.nrepl.inlined_deps.orchard.v0v5v5.orchard.java$class_info_STAR_.invoke(java.clj:187)
        at cider.nrepl.inlined_deps.orchard.v0v5v5.orchard.java$class_info.invokeStatic(java.clj:234)
        at cider.nrepl.inlined_deps.orchard.v0v5v5.orchard.java$class_info.invoke(java.clj:226)
        at cider.nrepl.inlined_deps.orchard.v0v5v5.orchard.java$eval8104$fn__8105.invoke(java.clj:376)
        at clojure.core$binding_conveyor_fn$fn__5754.invoke(core.clj:2030)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```
Note that it does not really prevent using Calva, but it may be breaking something I am not using.

Apparently, the same error was reported for clojure-emacs [1]

## Technical details

Version: 1.52.1
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Date: 2020-12-16T16:32:10.090Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.14-200.fc33.x86_64 (and also seen with Archlinux)
Calva: 2.0.134 - 2020-12-05
Java: OpenJDK 64-Bit Server VM Zulu15.28+13-CA (build 15.0.1+8, mixed mode, sharing)

Boot command: `lein update-in :dependencies conj '[nrepl"0.8.2"]' -- update-in :dependencies conj '[clj-kondo"2020.04.05"]' -- update-in :plugins conj '[cider/cider-nrepl"0.23.0"]' -- update-in '[:repl-options :nrepl-middleware]' conj '["cider.nrepl/cider-middleware"]' -- repl :headless`

[1] https://github.com/clojure-emacs/orchard/issues/100

**Comment by bpringe** [comment]
Thanks for the report. Lets see what can be done upstream.
