### ISSUE TITLE
Keyboard shortcuts not working, but command palette works just fine

### ISSUE THREAD

**Issue by vaeng** [BetterThanTomorrow/calva#909]
Issue Type: <b>Bug</b>

Ctrl Alt C + Ctrl Alt J is not recognized, but the command works with the command palette or the context menu. 

Redefining the shortcut is not helping either.

Here is the content of the developer console:

```
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'document' of undefined
	at c:\Users\chris.000\.vscode\extensions\betterthantomorrow.calva-2.0.140\out\extension.js:1:46272
	at l.fire (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:853:742
	at l.fire (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at b.acceptDocumentsAndEditorsDelta (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:738:816)
	at b.$acceptDocumentsAndEditorsDelta (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:736:848)
	at m._doInvokeHandler (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:892:926)
	at m._invokeHandler (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:892:618)
	at m._receiveRequest (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:891:252)
	at m._receiveOneMessage (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:890:6)
	at c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:888:136
	at l.fire (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at v.fire (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:233:787)
	at c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1094:104
	at l.fire (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at v.fire (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:233:787)
	at t.PersistentProtocol._receiveMessage (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:238:1004)
	at c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:235:927
	at l.fire (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:46:801)
	at p.acceptChunk (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:231:195)
	at c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:230:547
	at Socket.t (c:\Users\chris.000\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:240:822)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

Extension version: 2.0.140
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.20279

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.98GB free)|
|Process Argv|C:\\Users\\chris.000\\Documents\\Projekte\\deep-clojure --crash-reporter-id a71e9864-5295-404a-b0c0-2f31b0f0a2d7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
openlogontheside:30221877
python763:30178808
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
python504:30227505
vswsl492:30211401
wsl2promptcf:30224613
pythonvsdeb440:30237827
unusedprompt:30224610
folderexplorercf:30224615
openfilemenu:30224647
pythonvsded773:30236629
pythonvspyt875:30239451
vsjup459cf:30237188

```

</details>

**Comment by bpringe** [comment]
Hi. Try running the command "Toggle keybindings enabled". You may have accidentally hit the shortcut for this and disabled Calva's keybindings. I've actually removed the keybinding for this on the dev branch and this will be released soon, since it causes confusion. Let me know if this was your case.

**Comment by vaeng** [comment]
That did the trick. Thanks a lot.

> 
> 
> Hi. Try running the command "Toggle keybindings enabled". You may have accidentally hit the shortcut for this and disabled Calva's keybindings. I've actually removed the keybinding for this on the dev branch and this will be released soon, since it causes confusion. Let me know if this was your case.

**Comment by PEZ** [comment]
OMG. Good we are getting rid of that shortcut!
