### ISSUE TITLE
Some files not linted by default using clj-kondo via clojure-lsp that used to be linted by default using the clj-kondo extension 

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#960]
A report was made that a file like `/tmp/foo.clj` was not linted after uninstalling the clj-kondo extension in favor of kondo through clojure-lsp, whereas it was linted before uninstalling the extension.

**Comment by bpringe** [comment]
Here's the code in `/tmp/foo.clj`:

```clojure
(ns foo (:require [clojure.set :as set]))
(set/onion) ;; onion should be union
(defn x [])
(comment 
  x
  y
  (+  1)
  (+ (1 2 3))
  (/ "foo")
  )
```

This was reported by @borkdude. Just noting that here for later.

**Comment by borkdude** [comment]
Before:
![Screenshot 2021-01-18 at 18 29 06](https://user-images.githubusercontent.com/284934/104953083-0b206080-59c6-11eb-965a-e900b7ca8a20.png)

After:
![Screenshot 2021-01-18 at 18 29 18](https://user-images.githubusercontent.com/284934/104953085-0bb8f700-59c6-11eb-9a13-ca49e520815f.png)

**Comment by bpringe** [comment]
I noticed that when foo.clj is opened within another open project in VS Code, it is linted, but if it's just opened in a VS Code instance by itself, it's not.

When it's opened by itself, clojure-lsp returns the following for the document symbols:

```
[Trace - 10:57:40 AM] Sending request 'textDocument/documentSymbol - (7)'.
Params: {
    "textDocument": {
        "uri": "file:///tmp/foo.clj"
    }
}


[Trace - 10:57:40 AM] Received response 'textDocument/documentSymbol - (7)' in 1ms.
Result: []
```

I'm speculating this difference between the clj-kondo extension and clojure-lsp is that the extension would indiscriminately lint any file that was opened, and clojure-lsp in this latter case is not, for reasons I'm not sure yet, but it may have something to do with it not crawling the file, and therefore not having info on it, hence the above response showing no document symbols.

CC @ericdallo

**Comment by borkdude** [comment]
Correct, `clj-kondo` lints any file in the workspace.

**Comment by borkdude** [comment]
Another detail: the clj-kondo extension tries to resolve the .clj-kondo/config.edn by walking up the directories of the linted file (logic in the extension, link below) and when not found, it falls back on the project's .clj-kondo/config.edn instead (this is internal behavior of clj-kondo).

https://github.com/clj-kondo/clj-kondo.lsp/blob/master/server/src/clj_kondo/lsp_server/impl/server.clj#L106-L123

But even without a .clj-kondo/config.edn there should be linting.

**Comment by ericdallo** [comment]
Yeah, probably related to missing crawling, I think this could be solved by https://github.com/clojure-lsp/clojure-lsp/pull/261, but we'd need to test that after the merge

**Comment by bpringe** [comment]
@ericdallo I've narrowed it down to a null pointer exception thrown here: https://github.com/clojure-lsp/clojure-lsp/blob/7016f3652cbef75d6ef05bbb4f5e9551186740f0/src/clojure_lsp/feature/diagnostics.clj#L103, when that function is called like:

```clojure
(run-kondo-on-text! 
   "(ns foo (:require [clojure.set :as set]))\n\n(set/onion) ;; onion should be union\n(defn x [])\n\n(comment \n  x\n  y\n  (+  1)\n  (+ (1 2 3))\n  (/ \"foo\")\n  )" 
   :clj)
```

That's the text from above, as it was received in the `textDocument/didOpen` notification. See the error below, which I saw in `/tmp/clojure-lsp.out`, but also verified in the REPL.

```
WARN  clojure-lsp.feature.references: Cannot parse:  file:///tmp/foo.clj nil
java.lang.NullPointerException
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at clojure_lsp.shared$uri__GT_path.invokeStatic(shared.clj:43)
	at clojure_lsp.shared$uri__GT_path.invoke(shared.clj:43)
	at clojure_lsp.feature.diagnostics$kondo_args.invokeStatic(diagnostics.clj:82)
	at clojure_lsp.feature.diagnostics$kondo_args.invoke(diagnostics.clj:81)
	at clojure_lsp.feature.diagnostics$run_kondo_on_text_BANG_.invokeStatic(diagnostics.clj:104)
	at clojure_lsp.feature.diagnostics$run_kondo_on_text_BANG_.invoke(diagnostics.clj:103)
	at clojure_lsp.feature.diagnostics$kondo_find_diagnostics.invokeStatic(diagnostics.clj:108)
	at clojure_lsp.feature.diagnostics$kondo_find_diagnostics.invoke(diagnostics.clj:106)
	at clojure_lsp.feature.diagnostics$find_diagnostics.invokeStatic(diagnostics.clj:114)
	at clojure_lsp.feature.diagnostics$find_diagnostics.invoke(diagnostics.clj:113)
	at clojure_lsp.feature.references$safe_find_references.invokeStatic(references.clj:61)
	at clojure_lsp.feature.references$safe_find_references.invoke(references.clj:44)
	at clojure_lsp.feature.references$safe_find_references.invokeStatic(references.clj:46)
	at clojure_lsp.feature.references$safe_find_references.invoke(references.clj:44)
	at clojure_lsp.handlers$did_change.invokeStatic(handlers.clj:129)
	at clojure_lsp.handlers$did_change.invoke(handlers.clj:125)
	at clojure.lang.Var.invoke(Var.java:393)
	at clojure_lsp.main.LSPTextDocumentService.didChange(main.clj:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bpringe** [comment]
I'm not sure yet what the problem is, but it may be an issue with the way `kondo/run!` is called. I don't see any way that there is an issue before that. The text and file-type args to `run-kondo-on-text!` look fine.

**Comment by ericdallo** [comment]
yeah, if we didn't parsed correctly the code via `didOpen`, that can explain the issue.
Probably a issue parsing the `comment` macro?

**Comment by ericdallo** [comment]
Well, I'd suggest waiting for the clj-kondo analysis integration PR which should rely 100% on kondo analysis for that, which should fix the issue

**Comment by bpringe** [comment]
I'm excited for this PR, seems like a lot of things lately are related to it.

**Comment by ericdallo** [comment]
Yeah, it's the biggest refactor I saw on clojure-lsp 😅 and unfortunately, I think there is no easy way to set a feature flag for that PR, so we need to change a lot of places (almost all features) and test it very well

**Comment by bpringe** [comment]
I see. Just to add more info, I noticed the above error is coming from this line, when getting the kondo args for the `run!` call: https://github.com/clojure-lsp/clojure-lsp/blob/7016f3652cbef75d6ef05bbb4f5e9551186740f0/src/clojure_lsp/feature/diagnostics.clj#L82

This is because the `:project-root` is nil in this case, since no project is open, just the file. If that PR changes how this works, then hopefully it won't be a problem. :crossed_fingers:

**Comment by ericdallo** [comment]
Yeah, probably it will, we now use `some->` :)
https://github.com/clojure-lsp/clojure-lsp/pull/261/files#diff-fa419531b6cbafb2899aa71bcd5a5acee775a79480a43235c6f29fc5074cb1b6R68

**Comment by ericdallo** [comment]
@bpringe this should be fixed with https://github.com/clojure-lsp/clojure-lsp/releases/tag/2021.01.22-13.04.28 could you confirm please?

**Comment by bpringe** [comment]
Works now!
