### ISSUE TITLE
Got a error message that shadow-cljs is not  installed but it is installed 

### ISSUE THREAD

**Issue by ghost** [BetterThanTomorrow/calva#984]
Hello, 

Every time I start up vs code with the latest version of calva  in this project : https://github.com/RoelofWobben/giggin
I see this error: 

![afbeelding](https://user-images.githubusercontent.com/76750970/105642059-921e7e80-5e87-11eb-866a-3d76f9303ae8.png)

Looking at the /tmp/clojure.lsp.out I see this error message 

java.io.IOException: Cannot run program "shadow-cljs" (in directory "/home/roelof/learn-reagent-course-files/giggin"): error=2, No such file or directory

**Comment by bpringe** [comment]
Thanks for creating the issue and providing details. In slack you mentioned you installed the npm package shadow-cljs globally and still got the error? What happens if you run `shadow-cljs` in a terminal directly?

**Comment by ghost** [comment]
output 

`` `
shadow-cljs
shadow-cljs: command not found
```

**Comment by ghost** [comment]
and when I install it , I see 

```
yarn add --dev shadow-cljs
yarn add v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved 1 new dependency.
info Direct dependencies
└─ shadow-cljs@2.11.14
info All dependencies
└─ shadow-cljs@2.11.14
Done in 1.57s.
```

**Comment by bpringe** [comment]
You need to install it globally. You'll have to look up the proper yarn command if you want to use yarn, but for npm you can run `npm install -g shadow-cljs`.

To verify it's installed correctly, running `shadow-cljs -h` should show documentation for the command.

**Comment by ghost** [comment]
I did 

shadow-cljs -h  gives now this : 

``` 
shadow-cljs -h
Usage:
  shadow-cljs <action> <zero or more build ids>

Supported actions are:

     compile - ...
       watch - ...
       check - ...
     release - ...
   classpath - ...
   node-repl - ...
browser-repl - ...
   cljs-repl - ...
    clj-repl - ...
    ```

but still this in the outfile 

```
INFO  clojure-lsp.main: Starting server...
INFO  clojure-lsp.main: ====== LSP nrepl server started on port 36349
INFO  clojure-lsp.main: Initializing...
ERROR clojure-lsp.crawler: Error while looking up classpath info in /home/roelof/learn-reagent-course-files/giggin Cannot run program "shadow-cljs" (in directory "/home/roelof/learn-reagent-course-files/giggin"): error=2, No such file or directory
java.io.IOException: Cannot run program "shadow-cljs" (in directory "/home/roelof/learn-reagent-course-files/giggin"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
```

so the error is not gone

**Comment by bpringe** [comment]
Hmm, assuming that output is not from a previous try, that is very strange.

**Comment by bpringe** [comment]
What's your OS?

**Comment by ghost** [comment]
yep  very strange that shadow-cljs is installed and calva cannot find it.
Do not know if maybe that im running clojure in WSL can be a problem

**Comment by ghost** [comment]
I run VS Code on Windows and clojure on WSL2

**Comment by bpringe** [comment]
There may be something going on with that setup. Can you run `shadow-cljs -h` successfully from both Windows Powershell and from an integrated terminal in VS Code?

**Comment by bpringe** [comment]
I pulled down your linked project and did not see the error on my machine, so I think it definitely is related to your setup.

**Comment by ghost** [comment]
wierd
I see this in my out file 
```
INFO  clojure-lsp.main: Starting server...
INFO  clojure-lsp.main: ====== LSP nrepl server started on port 43917
INFO  clojure-lsp.main: Initializing...
ERROR clojure-lsp.crawler: Error while looking up classpath info in /home/roelof/learn-reagent-course-files/giggin Cannot run program "shadow-cljs" (in directory "/home/roelof/learn-reagent-course-files/giggin"): error=2, No such file or directory
java.io.IOException: Cannot run program "shadow-cljs" (in directory "/home/roelof/learn-reagent-course-files/giggin"): error=2, No such file or directory
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at java.base/java.lang.Runtime.exec(Runtime.java:592)
        at clojure.java.shell$sh.invokeStatic(shell.clj:113)
        at clojure.java.shell$sh.doInvoke(shell.clj:79)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at clojure_lsp.crawler$lookup_classpath.invokeStatic(crawler.clj:120)
        at clojure_lsp.crawler$lookup_classpath.invoke(crawler.clj:117)
        at clojure_lsp.crawler$try_project.invokeStatic(crawler.clj:136)
        at clojure_lsp.crawler$try_project.invoke(crawler.clj:132)
        at clojure_lsp.crawler$get_project_from$fn__24736.invoke(crawler.clj:159)
        at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
        at clojure.core.protocols$fn__8154.invokeStatic(protocols.clj:136)
        at clojure.core.protocols$fn__8154.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8114$G__8109__8123.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8146.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8146.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8088$G__8083__8101.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6828)
        at clojure.core$reduce.invoke(core.clj:6810)
        at clojure_lsp.crawler$get_project_from.invokeStatic(crawler.clj:157)
        at clojure_lsp.crawler$get_project_from.invoke(crawler.clj:156)
        at clojure_lsp.crawler$determine_dependencies.invokeStatic(crawler.clj:179)
        at clojure_lsp.crawler$determine_dependencies.invoke(crawler.clj:172)
        at clojure_lsp.handlers$initialize.invokeStatic(handlers.clj:96)
        at clojure_lsp.handlers$initialize.invoke(handlers.clj:86)
        at clojure.lang.Var.invoke(Var.java:393)
        at clojure_lsp.main$fn__28066$fn__28067.invoke(main.clj:303)
        at clojure_lsp.main.proxy$clojure_lsp.ClojureExtensions$LanguageServer$c8d5825a.initialize(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
        at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
        at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
        at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
        at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 47 more
INFO  clojure-lsp.producer: {:message Classpath lookup failed in clojure-lsp. Some features may not work correctly., :type :warning}
INFO  clojure-lsp.crawler: Crawling dir /home/roelof/learn-reagent-course-files/giggin/src
INFO  clojure-lsp.crawler: Crawling dir /home/roelof/learn-reagent-course-files/giggin/test
INFO  clojure-lsp.crawler: skipping classpath scan due to project hash match
DEBUG clojure-lsp.main: :initialize 442 ()
INFO  clojure-lsp.main: Initialized #object[org.eclipse.lsp4j.InitializedParams 0x510274e9 InitializedParams [
]]
WARN  clojure-lsp.main: {:settings {:clojure-lsp {}}}
DEBUG clojure-lsp.main: :didOpen 146 ()
DEBUG clojure-lsp.main: :documentSymbol 31 ([:codeAction #{35422045313}])
DEBUG clojure-lsp.main: Checking parent process 63 liveness
DEBUG clojure-lsp.main: Parent process 63 is running
DEBUG clojure-lsp.main: Checking parent process 63 liveness
DEBUG clojure-lsp.main: Parent process 63 is running
DEBUG clojure-lsp.main: Checking parent process 63 liveness
DEBUG clojure-lsp.main: Parent process 63 is running
DEBUG clojure-lsp.main: Checking parent process 63 liveness
DEBUG clojure-lsp.main: Parent process 63 is running
INFO  clojure-lsp.main: Shutting down
INFO  clojure-lsp.main: Exit
```

**Comment by ghost** [comment]
From the terminal of VS code I can run that command.
If I use in Windows powershell it cannot be run which is not wierd because powershell cannot see the WSL files as far as I know

**Comment by bpringe** [comment]
I'm thinking that maybe because the clojure-lsp server is spawned as a separate process on the host machine, it's being spawned on Windows, so maybe the call to shadow-cljs is being made on Windows. What you can do to verify this is install shadow-cljs globally on Windows, where powershell can run it, and then see if this problem persists.

**Comment by ghost** [comment]
oke, so install npm or yarn and node on Windows and then try again ?

**Comment by bpringe** [comment]
Yes

**Comment by bpringe** [comment]
Update: After @RoelofWobben installed shadow-cljs globally on Windows via npm, the warning no longer appears. This means the clojure-lsp classpath lookup call to shadow-cljs is being made on Windows, not WSL2, at least in this case.

**Comment by bpringe** [comment]
Another user has verified they do use shadow-cljs through WSL2 and do not have it installed on Windows, and they do not have this issue.

**Comment by bpringe** [comment]
@RoelofWobben Calva version 2.0.154 should fix the issue so that you don't get this error, even if you don't have shadow-cljs installed globally.
