### ISSUE TITLE
ERROR: Unhandled REPL handler exception processing message

### ISSUE THREAD

**Issue by clyfe** [BetterThanTomorrow/calva#994]
I sometimes get this in the terminal where calva starts `nrepl.cmdline`. Cljs via Figwheel main. It has no bad effects other than popping, I can still work normally. Calva v2.0.156. Stacktrace:

```
ERROR: Unhandled REPL handler exception processing message {:op complete, :ns riviera.core, :symbol s, :id 174, :session e12e0650-18a5-4f3f-a9f9-cd3fcddb5c3f, :context 0, :enhanced-cljs-completion? t}
java.lang.AssertionError: Assert failed: (symbol? ns)
        at cider.nrepl.inlined_deps.suitable.v0v3v5.suitable.compliment.sources.cljs.analysis$ns_meta.invokeStatic(analysis.cljc:257)
        at cider.nrepl.inlined_deps.suitable.v0v3v5.suitable.compliment.sources.cljs.analysis$ns_meta.invoke(analysis.cljc:257)
        at cider.nrepl.inlined_deps.suitable.v0v3v5.suitable.compliment.sources.cljs$ns_candidates$iter__25405__25409$fn__25410.invoke(cljs.cljc:82)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5420.invokeStatic(core.clj:139)
        at clojure.core$concat$cat__5513$fn__5514.invoke(core.clj:736)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:713)
        at clojure.core$next__5404.invokeStatic(core.clj:64)
        at clojure.core.protocols$fn__8183.invokeStatic(protocols.clj:169)
        at clojure.core.protocols$fn__8183.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8138$G__8133__8147.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8170.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8170.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8112$G__8107__8125.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6833)
        at clojure.core$group_by.invokeStatic(core.clj:7151)
        at clojure.core$group_by.invoke(core.clj:7151)
        at cider.nrepl.inlined_deps.suitable.v0v3v5.suitable.compliment.sources.cljs$distinct_candidates.invokeStatic(cljs.cljc:259)
        at cider.nrepl.inlined_deps.suitable.v0v3v5.suitable.compliment.sources.cljs$distinct_candidates.invoke(cljs.cljc:255)
        at cider.nrepl.inlined_deps.suitable.v0v3v5.suitable.compliment.sources.cljs$candidates.invokeStatic(cljs.cljc:295)
        at cider.nrepl.inlined_deps.suitable.v0v3v5.suitable.compliment.sources.cljs$candidates.invoke(cljs.cljc:285)
        at clojure.lang.Var.invoke(Var.java:393)
        at cider.nrepl.inlined_deps.compliment.v0v3v11.compliment.core$completions$fn__25206.invoke(core.clj:82)
        at clojure.core$map$fn__5885.invoke(core.clj:2759)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.core$seq__5420.invokeStatic(core.clj:139)
        at clojure.core$apply.invokeStatic(core.clj:662)
        at clojure.core$mapcat.invokeStatic(core.clj:2787)
        at clojure.core$mapcat.doInvoke(core.clj:2787)
        at clojure.lang.RestFn.invoke(RestFn.java:423)
        at cider.nrepl.inlined_deps.compliment.v0v3v11.compliment.core$completions.invokeStatic(core.clj:81)
        at cider.nrepl.inlined_deps.compliment.v0v3v11.compliment.core$completions.invoke(core.clj:54)
        at cider.nrepl.middleware.complete$complete.invokeStatic(complete.clj:38)
        at cider.nrepl.middleware.complete$complete.invoke(complete.clj:29)
        at cider.nrepl.middleware.complete$complete_reply.invokeStatic(complete.clj:52)
        at cider.nrepl.middleware.complete$complete_reply.invoke(complete.clj:51)
        at cider.nrepl.middleware.util.error_handling$eval11339$fn__11340.invoke(error_handling.clj:160)
        at clojure.lang.MultiFn.invoke(MultiFn.java:234)
        at cider.nrepl.middleware.complete$handle_complete.invokeStatic(complete.clj:64)
        at cider.nrepl.middleware.complete$handle_complete.invoke(complete.clj:63)
        at clojure.lang.Var.invoke(Var.java:388)
        at cider.nrepl$wrap_complete$fn__11098.invoke(nrepl.clj:140)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_classpath$fn__11090.invoke(nrepl.clj:134)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_spec$fn__11198.invoke(nrepl.clj:402)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_info$fn__11132.invoke(nrepl.clj:204)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_clojuredocs$fn__11264.invoke(nrepl.clj:512)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_apropos$fn__11082.invoke(nrepl.clj:126)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_xref$fn__11256.invoke(nrepl.clj:497)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_ns$fn__11158.invoke(nrepl.clj:286)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_slurp$fn__11074.invoke(nrepl.clj:118)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_trace$fn__11222.invoke(nrepl.clj:450)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at nrepl.middleware.interruptible_eval$interruptible_eval$fn__9912.invoke(interruptible_eval.clj:154)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at nrepl.middleware.session$add_stdin$fn__10229.invoke(session.clj:363)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at nrepl.middleware.load_file$wrap_load_file$fn__10579.invoke(load_file.clj:81)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_debug$fn__11108.invoke(nrepl.clj:160)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.piggieback$wrap_cljs_repl$fn__10031.invoke(piggieback_impl.clj:365)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_tracker$fn__11230.invoke(nrepl.clj:468)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_content_type$fn__11066.invoke(nrepl.clj:106)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at nrepl.middleware.sideloader$wrap_sideloader$fn__10666.invoke(sideloader.clj:102)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_out$fn__11166.invoke(nrepl.clj:320)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_enlighten$fn__11116.invoke(nrepl.clj:186)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_version$fn__11248.invoke(nrepl.clj:487)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at cider.nrepl$wrap_inspect$fn__11142.invoke(nrepl.clj:223)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at nrepl.middleware.session$session$fn__10214.invoke(session.clj:309)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at nrepl.middleware.caught$wrap_caught$fn__9847.invoke(caught.clj:97)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at nrepl.middleware.print$wrap_print$fn__9677.invoke(print.clj:234)
        at nrepl.middleware$wrap_conj_descriptor$fn__9465.invoke(middleware.clj:16)
        at nrepl.server$default_handler$fn__10710.invoke(server.clj:130)
        at nrepl.server$handle_STAR_.invokeStatic(server.clj:22)
        at nrepl.server$handle_STAR_.invoke(server.clj:19)
        at nrepl.server$handle$fn__10681.invoke(server.clj:39)
        at clojure.core$binding_conveyor_fn$fn__5773.invoke(core.clj:2034)
        at clojure.lang.AFn.call(AFn.java:18)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by bpringe** [comment]
Does this happen for every project or just that one? What version of nrepl and cider-nrepl are in your classpath? `lein classpath` or `clj -Spath`

**Comment by clyfe** [comment]
Start is:

`clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.8.3"} cider/cider-nrepl {:mvn/version "0.25.8"} cider/piggieback {:mvn/version "0.5.2"}}}' -m nrepl.cmdline --middleware "[cider.nrepl/cider-middleware cider.piggieback/wrap-cljs-repl]"`

Tried a bit, but didn't see it pop in other project.

**Comment by clyfe** [comment]
```shell
➜  riviera clj -Spath
src:resources:/home/clyfe/.m2/repository/borkdude/sci/0.2.1/sci-0.2.1.jar:/home/clyfe/.m2/repository/org/clojure/clojure/1.10.2/clojure-1.10.2.jar:/home/clyfe/.m2/repository/borkdude/edamame/0.0.11-alpha.28/edamame-0.0.11-alpha.28.jar:/home/clyfe/.m2/repository/borkdude/sci.impl.reflector/0.0.1/sci.impl.reflector-0.0.1.jar:/home/clyfe/.m2/repository/org/clojure/core.specs.alpha/0.2.56/core.specs.alpha-0.2.56.jar:/home/clyfe/.m2/repository/org/clojure/spec.alpha/0.2.194/spec.alpha-0.2.194.jar:/home/clyfe/.m2/repository/org/clojure/tools.reader/1.3.4/tools.reader-1.3.4.jar

```

**Comment by bpringe** [comment]
The versions of those jack-in deps isn't always the version being used (though maybe this is only or more so the case with lein). I would verify that the same versions you see in the jack-in command are what you see in your classpath in that project (`clj -Spath`).

**Comment by clyfe** [comment]
".m2/repository/cider/cider-nrepl/0.25.6/cider-nrepl-0.25.6.jar"
".m2/repository/nrepl/nrepl/0.8.2/nrepl-0.8.2.jar"

TIL; Don't `tools.deps` dowload the spec'd version?

**Comment by bpringe** [comment]
Without digging in to this, I'm not sure what's going on exactly, but with lein IIRC it downloads the first version it sees on the classpath. I'm not sure how tools.deps works, but I'm pretty sure I've seen it work as expected in cases where lein didn't (like latest version found being used).

If this is only happening with a particular project, I doubt it's something in your user deps.edn (if you have one). I'm guessing those two deps are also included by some deps in your project. 

I'd print your deps tree in that project and see if you see those older versions of those deps somewhere: https://clojure.org/reference/dep_expansion#_tree_printing
